2024-08-06 20:03:20,646 INFO    StreamThr :2149390 [internal.py:wandb_internal():86] W&B internal server running at pid: 2149390, started at: 2024-08-06 20:03:20.646031
2024-08-06 20:03:20,647 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: status
2024-08-06 20:03:20,647 INFO    WriterThread:2149390 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/run-frobmovt.wandb
2024-08-06 20:03:20,648 DEBUG   SenderThread:2149390 [sender.py:send():382] send: header
2024-08-06 20:03:20,648 DEBUG   SenderThread:2149390 [sender.py:send():382] send: run
2024-08-06 20:03:20,892 INFO    SenderThread:2149390 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files
2024-08-06 20:03:20,892 INFO    SenderThread:2149390 [sender.py:_start_run_threads():1136] run started: frobmovt with start time 1722945800.645897
2024-08-06 20:03:20,912 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 20:03:20,912 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: check_version
2024-08-06 20:03:21,009 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 20:03:21,023 DEBUG   HandlerThread:2149390 [system_info.py:__init__():32] System info init
2024-08-06 20:03:21,023 DEBUG   HandlerThread:2149390 [system_info.py:__init__():47] System info init done
2024-08-06 20:03:21,023 INFO    HandlerThread:2149390 [system_monitor.py:start():194] Starting system monitor
2024-08-06 20:03:21,023 INFO    SystemMonitor:2149390 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 20:03:21,023 INFO    HandlerThread:2149390 [system_monitor.py:probe():214] Collecting system info
2024-08-06 20:03:21,023 INFO    SystemMonitor:2149390 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 20:03:21,024 INFO    SystemMonitor:2149390 [interfaces.py:start():190] Started disk monitoring
2024-08-06 20:03:21,024 INFO    SystemMonitor:2149390 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 20:03:21,025 INFO    SystemMonitor:2149390 [interfaces.py:start():190] Started memory monitoring
2024-08-06 20:03:21,026 INFO    SystemMonitor:2149390 [interfaces.py:start():190] Started network monitoring
2024-08-06 20:03:21,032 DEBUG   HandlerThread:2149390 [system_info.py:probe():196] Probing system
2024-08-06 20:03:21,033 DEBUG   HandlerThread:2149390 [system_info.py:_probe_git():181] Probing git
2024-08-06 20:03:21,034 DEBUG   HandlerThread:2149390 [system_info.py:_probe_git():189] Probing git done
2024-08-06 20:03:21,034 DEBUG   HandlerThread:2149390 [system_info.py:probe():244] Probing system done
2024-08-06 20:03:21,034 DEBUG   HandlerThread:2149390 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T12:03:21.032499', 'startedAt': '2024-08-06T12:03:20.641186', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/qwen2-1.5b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1518.15825, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 2774.97, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2749.025, 'min': 800.0, 'max': 5500.0}, {'current': 1098.291, 'min': 800.0, 'max': 5500.0}, {'current': 2750.357, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2584.285, 'min': 800.0, 'max': 5500.0}, {'current': 2801.482, 'min': 800.0, 'max': 5500.0}, {'current': 2743.79, 'min': 800.0, 'max': 5600.0}, {'current': 2769.34, 'min': 800.0, 'max': 5600.0}, {'current': 2803.214, 'min': 800.0, 'max': 5600.0}, {'current': 2801.017, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2845.39, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2800.42, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1186.897, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1256.576, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 2837.434, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.37963485717773}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 20:03:21,035 INFO    HandlerThread:2149390 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 20:03:21,035 INFO    HandlerThread:2149390 [system_monitor.py:probe():227] Publishing system info
2024-08-06 20:03:21,035 DEBUG   HandlerThread:2149390 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 20:03:21,035 DEBUG   HandlerThread:2149390 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 20:03:21,035 DEBUG   HandlerThread:2149390 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 20:03:21,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/requirements.txt
2024-08-06 20:03:21,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/conda-environment.yaml
2024-08-06 20:03:22,716 DEBUG   HandlerThread:2149390 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 20:03:22,716 DEBUG   HandlerThread:2149390 [system_info.py:_save_code():90] Saving code
2024-08-06 20:03:22,717 DEBUG   HandlerThread:2149390 [system_info.py:_save_code():111] Saving code done
2024-08-06 20:03:22,717 DEBUG   HandlerThread:2149390 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 20:03:22,720 ERROR   HandlerThread:2149390 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 20:03:22,720 DEBUG   HandlerThread:2149390 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 20:03:22,720 INFO    HandlerThread:2149390 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 20:03:22,721 DEBUG   SenderThread:2149390 [sender.py:send():382] send: files
2024-08-06 20:03:22,721 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 20:03:22,721 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 20:03:22,723 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 20:03:22,723 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: stop_status
2024-08-06 20:03:22,724 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 20:03:22,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/conda-environment.yaml
2024-08-06 20:03:22,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/code/llama/gmm.py
2024-08-06 20:03:22,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/wandb-metadata.json
2024-08-06 20:03:22,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/code
2024-08-06 20:03:22,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/code/llama
2024-08-06 20:03:22,916 DEBUG   SenderThread:2149390 [sender.py:send():382] send: telemetry
2024-08-06 20:03:22,916 DEBUG   SenderThread:2149390 [sender.py:send():382] send: config
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: telemetry
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:22,917 WARNING SenderThread:2149390 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: telemetry
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: telemetry
2024-08-06 20:03:22,917 DEBUG   SenderThread:2149390 [sender.py:send():382] send: config
2024-08-06 20:03:23,079 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124
2024-08-06 20:03:23,079 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:23,079 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E922144BB6AC60</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:23,372 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2
2024-08-06 20:03:23,372 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5184', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:23,372 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E922145F9DEB1C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:23,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:24,381 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124
2024-08-06 20:03:24,381 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:24,381 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E922149B2F630C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:24,610 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2
2024-08-06 20:03:24,610 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5184', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:24,610 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E92214A967D6D7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:24,610 INFO    wandb-upload_0:2149390 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 20:03:24,886 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send():382] send: metric
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send():382] send: history
2024-08-06 20:03:24,887 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:03:24,887 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:03:24,892 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/wandb-summary.json
2024-08-06 20:03:25,888 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 20:03:25,893 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:26,607 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124
2024-08-06 20:03:26,608 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:26,608 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E922151FD6FF80</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:26,685 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:03:26,685 DEBUG   SenderThread:2149390 [sender.py:send():382] send: history
2024-08-06 20:03:26,685 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:03:26,685 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:03:26,893 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/wandb-summary.json
2024-08-06 20:03:26,893 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:27,107 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120323Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=47f34f57b68881052796b2932de932febe800b7bed9248915ccdcad725b194d2
2024-08-06 20:03:27,108 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5184', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:27,108 ERROR   wandb-upload_0:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E922153E44C83C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:03:27,893 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:28,354 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:03:28,354 DEBUG   SenderThread:2149390 [sender.py:send():382] send: history
2024-08-06 20:03:28,355 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:03:28,355 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:03:28,894 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/wandb-summary.json
2024-08-06 20:03:28,894 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:29,894 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:30,173 DEBUG   HandlerThread:2149390 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:03:30,174 DEBUG   SenderThread:2149390 [sender.py:send():382] send: history
2024-08-06 20:03:30,174 DEBUG   SenderThread:2149390 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:03:30,174 INFO    SenderThread:2149390 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:03:30,895 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/wandb-summary.json
2024-08-06 20:03:30,895 INFO    Thread-12 :2149390 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_200320-frobmovt/files/output.log
2024-08-06 20:03:31,123 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T120322Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=ec8bd8761a51a46a82eb9e817b0909b8e947e39dbc4425548d6b785251b18124
2024-08-06 20:03:31,123 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:03:31,123 ERROR   wandb-upload_1:2149390 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/frobmovt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/frobmovt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E922162D066892</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
