2024-08-06 19:03:59,279 INFO    StreamThr :2120566 [internal.py:wandb_internal():86] W&B internal server running at pid: 2120566, started at: 2024-08-06 19:03:59.279532
2024-08-06 19:03:59,281 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status
2024-08-06 19:03:59,281 INFO    WriterThread:2120566 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/run-xgh3y6sr.wandb
2024-08-06 19:03:59,281 DEBUG   SenderThread:2120566 [sender.py:send():382] send: header
2024-08-06 19:03:59,281 DEBUG   SenderThread:2120566 [sender.py:send():382] send: run
2024-08-06 19:03:59,507 INFO    SenderThread:2120566 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files
2024-08-06 19:03:59,507 INFO    SenderThread:2120566 [sender.py:_start_run_threads():1136] run started: xgh3y6sr with start time 1722942239.279492
2024-08-06 19:03:59,520 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 19:03:59,520 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: check_version
2024-08-06 19:03:59,621 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 19:03:59,625 DEBUG   HandlerThread:2120566 [system_info.py:__init__():32] System info init
2024-08-06 19:03:59,625 DEBUG   HandlerThread:2120566 [system_info.py:__init__():47] System info init done
2024-08-06 19:03:59,625 INFO    HandlerThread:2120566 [system_monitor.py:start():194] Starting system monitor
2024-08-06 19:03:59,626 INFO    SystemMonitor:2120566 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 19:03:59,626 INFO    HandlerThread:2120566 [system_monitor.py:probe():214] Collecting system info
2024-08-06 19:03:59,626 INFO    SystemMonitor:2120566 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 19:03:59,626 INFO    SystemMonitor:2120566 [interfaces.py:start():190] Started disk monitoring
2024-08-06 19:03:59,627 INFO    SystemMonitor:2120566 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 19:03:59,627 INFO    SystemMonitor:2120566 [interfaces.py:start():190] Started memory monitoring
2024-08-06 19:03:59,628 INFO    SystemMonitor:2120566 [interfaces.py:start():190] Started network monitoring
2024-08-06 19:03:59,634 DEBUG   HandlerThread:2120566 [system_info.py:probe():196] Probing system
2024-08-06 19:03:59,635 DEBUG   HandlerThread:2120566 [system_info.py:_probe_git():181] Probing git
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_info.py:_probe_git():189] Probing git done
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_info.py:probe():244] Probing system done
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T11:03:59.634096', 'startedAt': '2024-08-06T11:03:59.274567', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2b', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2272.352178571429, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 3891.78, 'min': 800.0, 'max': 5500.0}, {'current': 3709.336, 'min': 800.0, 'max': 5500.0}, {'current': 3746.29, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3705.63, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3819.465, 'min': 800.0, 'max': 5500.0}, {'current': 4048.86, 'min': 800.0, 'max': 5500.0}, {'current': 4477.194, 'min': 800.0, 'max': 5600.0}, {'current': 4065.061, 'min': 800.0, 'max': 5600.0}, {'current': 3979.983, 'min': 800.0, 'max': 5600.0}, {'current': 3702.412, 'min': 800.0, 'max': 5600.0}, {'current': 5152.643, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3860.638, 'min': 800.0, 'max': 5500.0}, {'current': 5371.163, 'min': 800.0, 'max': 5500.0}, {'current': 3607.024, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.3673515319824}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 19:03:59,637 INFO    HandlerThread:2120566 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 19:03:59,637 INFO    HandlerThread:2120566 [system_monitor.py:probe():227] Publishing system info
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 19:03:59,637 DEBUG   HandlerThread:2120566 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 19:04:00,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/conda-environment.yaml
2024-08-06 19:04:00,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/requirements.txt
2024-08-06 19:04:01,316 DEBUG   HandlerThread:2120566 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 19:04:01,316 DEBUG   HandlerThread:2120566 [system_info.py:_save_code():90] Saving code
2024-08-06 19:04:01,317 DEBUG   HandlerThread:2120566 [system_info.py:_save_code():111] Saving code done
2024-08-06 19:04:01,317 DEBUG   HandlerThread:2120566 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 19:04:01,320 ERROR   HandlerThread:2120566 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 19:04:01,320 DEBUG   HandlerThread:2120566 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 19:04:01,320 INFO    HandlerThread:2120566 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 19:04:01,321 DEBUG   SenderThread:2120566 [sender.py:send():382] send: files
2024-08-06 19:04:01,321 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 19:04:01,321 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 19:04:01,323 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:04:01,323 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:04:01,323 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:04:01,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/conda-environment.yaml
2024-08-06 19:04:01,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-metadata.json
2024-08-06 19:04:01,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/code/llama/gmm.py
2024-08-06 19:04:01,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/code/llama
2024-08-06 19:04:01,507 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/code
2024-08-06 19:04:01,606 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce
2024-08-06 19:04:01,607 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:01,607 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91ED715096179</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:01,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac
2024-08-06 19:04:01,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:01,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91ED7192519FD</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:02,838 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce
2024-08-06 19:04:02,838 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:02,838 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91ED75E6BDA2A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:03,037 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac
2024-08-06 19:04:03,037 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:03,037 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91ED7695964C8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:03,037 INFO    wandb-upload_1:2120566 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:04:03,663 DEBUG   SenderThread:2120566 [sender.py:send():382] send: telemetry
2024-08-06 19:04:03,663 DEBUG   SenderThread:2120566 [sender.py:send():382] send: config
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: telemetry
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:03,664 WARNING SenderThread:2120566 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: telemetry
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: telemetry
2024-08-06 19:04:03,664 DEBUG   SenderThread:2120566 [sender.py:send():382] send: config
2024-08-06 19:04:04,508 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:04,665 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:04:05,067 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce
2024-08-06 19:04:05,067 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:05,067 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91ED7E33C26A4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:05,091 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send():382] send: metric
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:05,092 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:05,093 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:05,508 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:05,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac
2024-08-06 19:04:05,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:05,737 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91ED7F2EF8071</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:06,508 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:07,508 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:08,547 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:08,547 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:08,548 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:08,548 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:09,509 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:09,509 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:09,671 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce
2024-08-06 19:04:09,671 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:09,671 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91ED8F595FCDB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:09,951 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac
2024-08-06 19:04:09,951 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:09,951 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91ED9057AF258</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:10,509 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:10,548 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:04:11,786 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:11,786 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:11,786 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:11,787 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:12,509 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:13,510 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:13,716 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:13,758 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:14,510 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:15,229 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:15,230 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:15,230 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:15,230 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:15,510 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:16,231 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:04:16,323 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:04:16,323 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:04:16,324 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:04:17,148 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:17,511 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:18,150 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=822f6d8574fb838ff1fb22898417e85fe72faecab0f1e9e671d7d0be99d8b2ac
2024-08-06 19:04:18,150 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:18,150 ERROR   wandb-upload_1:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E91EDAEE527C72</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:18,255 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T110401Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f5f339016d830d34eddbede0ea0ceef2d504e245822d3506dcc0917d93cab3ce
2024-08-06 19:04:18,255 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5182', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:04:18,255 ERROR   wandb-upload_0:2120566 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/xgh3y6sr/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/xgh3y6sr/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E91EDAF5452E4F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:04:18,511 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:18,666 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:18,667 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:18,667 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:18,667 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:19,511 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:19,724 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:20,511 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:21,512 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:21,667 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:04:21,977 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:21,977 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:21,977 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:21,978 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:22,020 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:22,512 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:23,512 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:24,512 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:25,315 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:25,316 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:25,316 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:25,316 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:04:25,359 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:25,402 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:25,513 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/wandb-summary.json
2024-08-06 19:04:27,316 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:04:27,513 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:27,730 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:27,772 ERROR   FileStreamThread:2120566 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: http://dian.sea-group.org:9098/files/mobius/huggingface/xgh3y6sr/file_stream
NoneType: None
2024-08-06 19:04:28,513 INFO    Thread-12 :2120566 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_190359-xgh3y6sr/files/output.log
2024-08-06 19:04:28,695 DEBUG   HandlerThread:2120566 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:04:28,695 DEBUG   SenderThread:2120566 [sender.py:send():382] send: history
2024-08-06 19:04:28,695 DEBUG   SenderThread:2120566 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:04:28,696 INFO    SenderThread:2120566 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
