2024-08-08 19:28:18,645 INFO    StreamThr :330933 [internal.py:wandb_internal():86] W&B internal server running at pid: 330933, started at: 2024-08-08 19:28:18.645378
2024-08-08 19:28:18,646 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: status
2024-08-08 19:28:18,647 INFO    WriterThread:330933 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/run-l9ni6zpo.wandb
2024-08-08 19:28:18,647 DEBUG   SenderThread:330933 [sender.py:send():382] send: header
2024-08-08 19:28:18,667 DEBUG   SenderThread:330933 [sender.py:send():382] send: run
2024-08-08 19:28:18,923 INFO    SenderThread:330933 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files
2024-08-08 19:28:18,924 INFO    SenderThread:330933 [sender.py:_start_run_threads():1136] run started: l9ni6zpo with start time 1723116498.645383
2024-08-08 19:28:18,929 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 19:28:18,929 DEBUG   SenderThread:330933 [sender.py:send_request():409] send_request: check_version
2024-08-08 19:28:19,038 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 19:28:19,047 DEBUG   HandlerThread:330933 [system_info.py:__init__():32] System info init
2024-08-08 19:28:19,047 DEBUG   HandlerThread:330933 [system_info.py:__init__():47] System info init done
2024-08-08 19:28:19,047 INFO    HandlerThread:330933 [system_monitor.py:start():194] Starting system monitor
2024-08-08 19:28:19,047 INFO    SystemMonitor:330933 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 19:28:19,047 INFO    HandlerThread:330933 [system_monitor.py:probe():214] Collecting system info
2024-08-08 19:28:19,047 INFO    SystemMonitor:330933 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 19:28:19,048 INFO    SystemMonitor:330933 [interfaces.py:start():190] Started disk monitoring
2024-08-08 19:28:19,048 INFO    SystemMonitor:330933 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 19:28:19,048 INFO    SystemMonitor:330933 [interfaces.py:start():190] Started memory monitoring
2024-08-08 19:28:19,049 INFO    SystemMonitor:330933 [interfaces.py:start():190] Started network monitoring
2024-08-08 19:28:19,054 DEBUG   HandlerThread:330933 [system_info.py:probe():196] Probing system
2024-08-08 19:28:19,055 DEBUG   HandlerThread:330933 [system_info.py:_probe_git():181] Probing git
2024-08-08 19:28:19,058 DEBUG   HandlerThread:330933 [system_info.py:_probe_git():189] Probing git done
2024-08-08 19:28:19,058 DEBUG   HandlerThread:330933 [system_info.py:probe():244] Probing system done
2024-08-08 19:28:19,058 DEBUG   HandlerThread:330933 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T11:28:19.054735', 'startedAt': '2024-08-08T11:28:18.643703', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1634.1970000000001, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5440.172, 'min': 800.0, 'max': 5500.0}, {'current': 1648.739, 'min': 800.0, 'max': 5500.0}, {'current': 5023.351, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5256.037, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3675.766, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5461.088, 'min': 800.0, 'max': 5600.0}, {'current': 3976.247, 'min': 800.0, 'max': 5600.0}, {'current': 3785.673, 'min': 800.0, 'max': 5600.0}, {'current': 4334.431, 'min': 800.0, 'max': 5600.0}, {'current': 5435.243, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 3824.807, 'min': 800.0, 'max': 4300.0}, {'current': 1500.689, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0384292602539}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 19:28:19,059 INFO    HandlerThread:330933 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 19:28:19,059 INFO    HandlerThread:330933 [system_monitor.py:probe():227] Publishing system info
2024-08-08 19:28:19,059 DEBUG   HandlerThread:330933 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 19:28:19,059 DEBUG   HandlerThread:330933 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 19:28:19,059 DEBUG   HandlerThread:330933 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 19:28:19,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/conda-environment.yaml
2024-08-08 19:28:19,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/requirements.txt
2024-08-08 19:28:20,746 DEBUG   HandlerThread:330933 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 19:28:20,746 DEBUG   HandlerThread:330933 [system_info.py:_save_code():90] Saving code
2024-08-08 19:28:20,747 DEBUG   HandlerThread:330933 [system_info.py:_save_code():111] Saving code done
2024-08-08 19:28:20,747 DEBUG   HandlerThread:330933 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 19:28:20,787 DEBUG   HandlerThread:330933 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 19:28:20,788 INFO    HandlerThread:330933 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 19:28:20,790 DEBUG   SenderThread:330933 [sender.py:send():382] send: files
2024-08-08 19:28:20,790 INFO    SenderThread:330933 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 19:28:20,791 INFO    SenderThread:330933 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 19:28:20,791 INFO    SenderThread:330933 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 19:28:20,796 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 19:28:20,796 DEBUG   SenderThread:330933 [sender.py:send_request():409] send_request: stop_status
2024-08-08 19:28:20,800 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 19:28:20,923 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/conda-environment.yaml
2024-08-08 19:28:20,923 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/code/llama/gmm.py
2024-08-08 19:28:20,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/diff.patch
2024-08-08 19:28:20,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/wandb-metadata.json
2024-08-08 19:28:20,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/code/llama
2024-08-08 19:28:20,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/code
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: telemetry
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: config
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: telemetry
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:21,041 WARNING SenderThread:330933 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: telemetry
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: telemetry
2024-08-08 19:28:21,041 DEBUG   SenderThread:330933 [sender.py:send():382] send: config
2024-08-08 19:28:21,088 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa
2024-08-08 19:28:21,088 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5254', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:21,088 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BD540808560A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:21,235 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d
2024-08-08 19:28:21,235 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:21,235 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BD540CCE7209</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:21,830 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96
2024-08-08 19:28:21,830 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291711', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:21,830 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BD5407C20821</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:21,923 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/output.log
2024-08-08 19:28:22,477 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa
2024-08-08 19:28:22,477 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5254', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:22,477 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BD54559F78ED</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:22,562 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d
2024-08-08 19:28:22,562 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:22,562 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BD545FE1C054</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:22,562 INFO    wandb-upload_1:330933 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:28:23,136 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96
2024-08-08 19:28:23,136 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291711', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:23,136 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BD5478A69657</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:23,428 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 19:28:23,428 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:23,434 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:23,434 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:23,434 DEBUG   SenderThread:330933 [sender.py:send():382] send: metric
2024-08-08 19:28:23,434 DEBUG   SenderThread:330933 [sender.py:send():382] send: history
2024-08-08 19:28:23,434 DEBUG   SenderThread:330933 [sender.py:send_request():409] send_request: summary_record
2024-08-08 19:28:23,434 INFO    SenderThread:330933 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:28:23,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/output.log
2024-08-08 19:28:23,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/wandb-summary.json
2024-08-08 19:28:24,435 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 19:28:24,779 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=97efb49a0221b744edc25bd877fe7c36061970914d58f3078862f45122b03afa
2024-08-08 19:28:24,780 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5254', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:24,780 ERROR   wandb-upload_0:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BD54E426A177</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:24,833 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6f98f8e5db38e7c8b92d748e0866b87351259f31b35ce5a87f636a1b83b2946d
2024-08-08 19:28:24,833 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:24,833 ERROR   wandb-upload_1:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BD54E62E45F9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:25,688 DEBUG   HandlerThread:330933 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 19:28:25,688 DEBUG   SenderThread:330933 [sender.py:send():382] send: history
2024-08-08 19:28:25,688 DEBUG   SenderThread:330933 [sender.py:send_request():409] send_request: summary_record
2024-08-08 19:28:25,688 INFO    SenderThread:330933 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:28:25,700 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/l9ni6zpo/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T112820Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d5b8dfe03d4d1ba699d036d38696fc68ffdd1376c70c990474c904db01c7ae96
2024-08-08 19:28:25,700 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291711', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:28:25,700 ERROR   wandb-upload_2:330933 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/l9ni6zpo/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/l9ni6zpo/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BD55088CB206</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:28:25,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/output.log
2024-08-08 19:28:25,924 INFO    Thread-12 :330933 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_192818-l9ni6zpo/files/wandb-summary.json
