2024-08-08 18:07:22,279 INFO    StreamThr :312600 [internal.py:wandb_internal():86] W&B internal server running at pid: 312600, started at: 2024-08-08 18:07:22.279704
2024-08-08 18:07:22,281 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: status
2024-08-08 18:07:22,281 INFO    WriterThread:312600 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/run-hy9pk7p0.wandb
2024-08-08 18:07:22,281 DEBUG   SenderThread:312600 [sender.py:send():382] send: header
2024-08-08 18:07:22,310 DEBUG   SenderThread:312600 [sender.py:send():382] send: run
2024-08-08 18:07:22,534 INFO    SenderThread:312600 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files
2024-08-08 18:07:22,534 INFO    SenderThread:312600 [sender.py:_start_run_threads():1136] run started: hy9pk7p0 with start time 1723111642.279578
2024-08-08 18:07:22,548 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 18:07:22,548 DEBUG   SenderThread:312600 [sender.py:send_request():409] send_request: check_version
2024-08-08 18:07:22,661 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 18:07:22,670 DEBUG   HandlerThread:312600 [system_info.py:__init__():32] System info init
2024-08-08 18:07:22,670 DEBUG   HandlerThread:312600 [system_info.py:__init__():47] System info init done
2024-08-08 18:07:22,670 INFO    HandlerThread:312600 [system_monitor.py:start():194] Starting system monitor
2024-08-08 18:07:22,670 INFO    SystemMonitor:312600 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 18:07:22,670 INFO    HandlerThread:312600 [system_monitor.py:probe():214] Collecting system info
2024-08-08 18:07:22,670 INFO    SystemMonitor:312600 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 18:07:22,671 INFO    SystemMonitor:312600 [interfaces.py:start():190] Started disk monitoring
2024-08-08 18:07:22,671 INFO    SystemMonitor:312600 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 18:07:22,671 INFO    SystemMonitor:312600 [interfaces.py:start():190] Started memory monitoring
2024-08-08 18:07:22,672 INFO    SystemMonitor:312600 [interfaces.py:start():190] Started network monitoring
2024-08-08 18:07:22,680 DEBUG   HandlerThread:312600 [system_info.py:probe():196] Probing system
2024-08-08 18:07:22,682 DEBUG   HandlerThread:312600 [system_info.py:_probe_git():181] Probing git
2024-08-08 18:07:22,687 DEBUG   HandlerThread:312600 [system_info.py:_probe_git():189] Probing git done
2024-08-08 18:07:22,687 DEBUG   HandlerThread:312600 [system_info.py:probe():244] Probing system done
2024-08-08 18:07:22,687 DEBUG   HandlerThread:312600 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T10:07:22.680976', 'startedAt': '2024-08-08T10:07:22.275327', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2239.4004999999997, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 3036.927, 'min': 800.0, 'max': 5500.0}, {'current': 5158.722, 'min': 800.0, 'max': 5500.0}, {'current': 4863.274, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5093.115, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2133.983, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4638.672, 'min': 800.0, 'max': 5600.0}, {'current': 4374.555, 'min': 800.0, 'max': 5600.0}, {'current': 2616.373, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1355.346, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4041.223, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0352783203125}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 18:07:22,687 INFO    HandlerThread:312600 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 18:07:22,687 INFO    HandlerThread:312600 [system_monitor.py:probe():227] Publishing system info
2024-08-08 18:07:22,687 DEBUG   HandlerThread:312600 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 18:07:22,688 DEBUG   HandlerThread:312600 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 18:07:22,688 DEBUG   HandlerThread:312600 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 18:07:23,534 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/requirements.txt
2024-08-08 18:07:23,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/conda-environment.yaml
2024-08-08 18:07:24,353 DEBUG   HandlerThread:312600 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 18:07:24,353 DEBUG   HandlerThread:312600 [system_info.py:_save_code():90] Saving code
2024-08-08 18:07:24,354 DEBUG   HandlerThread:312600 [system_info.py:_save_code():111] Saving code done
2024-08-08 18:07:24,354 DEBUG   HandlerThread:312600 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 18:07:24,375 DEBUG   HandlerThread:312600 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 18:07:24,375 INFO    HandlerThread:312600 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 18:07:24,376 DEBUG   SenderThread:312600 [sender.py:send():382] send: files
2024-08-08 18:07:24,376 INFO    SenderThread:312600 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 18:07:24,376 INFO    SenderThread:312600 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 18:07:24,376 INFO    SenderThread:312600 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 18:07:24,379 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 18:07:24,379 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 18:07:24,379 DEBUG   SenderThread:312600 [sender.py:send_request():409] send_request: stop_status
2024-08-08 18:07:24,534 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/conda-environment.yaml
2024-08-08 18:07:24,534 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/code/llama/gmm.py
2024-08-08 18:07:24,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/diff.patch
2024-08-08 18:07:24,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/wandb-metadata.json
2024-08-08 18:07:24,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/code/llama
2024-08-08 18:07:24,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/code
2024-08-08 18:07:24,561 DEBUG   SenderThread:312600 [sender.py:send():382] send: telemetry
2024-08-08 18:07:24,561 DEBUG   SenderThread:312600 [sender.py:send():382] send: config
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: telemetry
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:24,562 WARNING SenderThread:312600 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: telemetry
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: telemetry
2024-08-08 18:07:24,562 DEBUG   SenderThread:312600 [sender.py:send():382] send: config
2024-08-08 18:07:24,605 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1
2024-08-08 18:07:24,605 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5248', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:24,605 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8E94BA5AA53</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:24,706 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4
2024-08-08 18:07:24,706 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:24,706 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8E94F6E6208</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:24,954 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6
2024-08-08 18:07:24,954 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291945', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:24,954 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8E94D88BC71</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:25,534 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/output.log
2024-08-08 18:07:25,825 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1
2024-08-08 18:07:25,825 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5248', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:25,825 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8E9941909DC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:25,970 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4
2024-08-08 18:07:25,970 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:25,970 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8E99CB4BB4E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:25,970 INFO    wandb-upload_1:312600 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 18:07:26,149 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6
2024-08-08 18:07:26,149 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291945', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:26,150 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8E9A47F86D3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:26,846 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send():382] send: metric
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send():382] send: history
2024-08-08 18:07:26,847 DEBUG   SenderThread:312600 [sender.py:send_request():409] send_request: summary_record
2024-08-08 18:07:26,847 INFO    SenderThread:312600 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 18:07:27,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/output.log
2024-08-08 18:07:27,535 INFO    Thread-12 :312600 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_180722-hy9pk7p0/files/wandb-summary.json
2024-08-08 18:07:27,848 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 18:07:28,067 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3f1b69b022075ffadadcac9e0f61e3bf2a60be0c2b8d25694d4387b7ecb49ba1
2024-08-08 18:07:28,067 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5248', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:28,067 ERROR   wandb-upload_0:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B8EA19BB9E6B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:28,499 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fc59845b5371759e5cb394d21688bc40590ee71f0666caedc55ae52c4048b2b4
2024-08-08 18:07:28,499 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:28,499 ERROR   wandb-upload_1:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B8EA338D2751</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:28,623 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/hy9pk7p0/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T100724Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=8f4e92bbbc6af17ef2eb319338b39c04ca40696f4feb1d35073979f2fa8404a6
2024-08-08 18:07:28,623 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291945', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 18:07:28,623 ERROR   wandb-upload_2:312600 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/hy9pk7p0/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/hy9pk7p0/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B8EA320E474F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 18:07:28,966 DEBUG   HandlerThread:312600 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 18:07:28,967 DEBUG   SenderThread:312600 [sender.py:send():382] send: history
2024-08-08 18:07:28,967 DEBUG   SenderThread:312600 [sender.py:send_request():409] send_request: summary_record
2024-08-08 18:07:28,967 INFO    SenderThread:312600 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
