2024-08-08 19:38:49,288 INFO    StreamThr :335697 [internal.py:wandb_internal():86] W&B internal server running at pid: 335697, started at: 2024-08-08 19:38:49.288087
2024-08-08 19:38:49,288 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: status
2024-08-08 19:38:49,289 INFO    WriterThread:335697 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/run-bvmwm3vs.wandb
2024-08-08 19:38:49,289 DEBUG   SenderThread:335697 [sender.py:send():382] send: header
2024-08-08 19:38:49,317 DEBUG   SenderThread:335697 [sender.py:send():382] send: run
2024-08-08 19:38:50,136 INFO    SenderThread:335697 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files
2024-08-08 19:38:50,136 INFO    SenderThread:335697 [sender.py:_start_run_threads():1136] run started: bvmwm3vs with start time 1723117129.288103
2024-08-08 19:38:50,145 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 19:38:50,145 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: check_version
2024-08-08 19:38:50,257 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 19:38:50,266 DEBUG   HandlerThread:335697 [system_info.py:__init__():32] System info init
2024-08-08 19:38:50,266 DEBUG   HandlerThread:335697 [system_info.py:__init__():47] System info init done
2024-08-08 19:38:50,266 INFO    HandlerThread:335697 [system_monitor.py:start():194] Starting system monitor
2024-08-08 19:38:50,266 INFO    SystemMonitor:335697 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 19:38:50,266 INFO    HandlerThread:335697 [system_monitor.py:probe():214] Collecting system info
2024-08-08 19:38:50,267 INFO    SystemMonitor:335697 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 19:38:50,267 INFO    SystemMonitor:335697 [interfaces.py:start():190] Started disk monitoring
2024-08-08 19:38:50,267 INFO    SystemMonitor:335697 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 19:38:50,268 INFO    SystemMonitor:335697 [interfaces.py:start():190] Started memory monitoring
2024-08-08 19:38:50,268 INFO    SystemMonitor:335697 [interfaces.py:start():190] Started network monitoring
2024-08-08 19:38:50,277 DEBUG   HandlerThread:335697 [system_info.py:probe():196] Probing system
2024-08-08 19:38:50,279 DEBUG   HandlerThread:335697 [system_info.py:_probe_git():181] Probing git
2024-08-08 19:38:50,283 DEBUG   HandlerThread:335697 [system_info.py:_probe_git():189] Probing git done
2024-08-08 19:38:50,283 DEBUG   HandlerThread:335697 [system_info.py:probe():244] Probing system done
2024-08-08 19:38:50,283 DEBUG   HandlerThread:335697 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T11:38:50.277803', 'startedAt': '2024-08-08T11:38:49.282576', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'gbmm'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2037.3912500000001, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 4797.401, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5033.675, 'min': 800.0, 'max': 5500.0}, {'current': 5305.997, 'min': 800.0, 'max': 5500.0}, {'current': 5378.486, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3187.203, 'min': 800.0, 'max': 5600.0}, {'current': 1442.721, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2692.843, 'min': 800.0, 'max': 5500.0}, {'current': 2724.62, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1884.009, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.04068756103516}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 19:38:50,283 INFO    HandlerThread:335697 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 19:38:50,283 INFO    HandlerThread:335697 [system_monitor.py:probe():227] Publishing system info
2024-08-08 19:38:50,283 DEBUG   HandlerThread:335697 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 19:38:50,283 DEBUG   HandlerThread:335697 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 19:38:50,284 DEBUG   HandlerThread:335697 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 19:38:51,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/requirements.txt
2024-08-08 19:38:51,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/conda-environment.yaml
2024-08-08 19:38:51,945 DEBUG   HandlerThread:335697 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 19:38:51,945 DEBUG   HandlerThread:335697 [system_info.py:_save_code():90] Saving code
2024-08-08 19:38:51,946 DEBUG   HandlerThread:335697 [system_info.py:_save_code():111] Saving code done
2024-08-08 19:38:51,946 DEBUG   HandlerThread:335697 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 19:38:51,985 DEBUG   HandlerThread:335697 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 19:38:51,986 INFO    HandlerThread:335697 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 19:38:51,989 DEBUG   SenderThread:335697 [sender.py:send():382] send: files
2024-08-08 19:38:51,989 INFO    SenderThread:335697 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 19:38:51,990 INFO    SenderThread:335697 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 19:38:51,990 INFO    SenderThread:335697 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 19:38:51,997 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 19:38:51,997 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 19:38:51,998 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: stop_status
2024-08-08 19:38:52,136 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/conda-environment.yaml
2024-08-08 19:38:52,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/wandb-metadata.json
2024-08-08 19:38:52,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/code/llama/gmm.py
2024-08-08 19:38:52,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/diff.patch
2024-08-08 19:38:52,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/code
2024-08-08 19:38:52,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/code/llama
2024-08-08 19:38:52,251 DEBUG   SenderThread:335697 [sender.py:send():382] send: telemetry
2024-08-08 19:38:52,251 DEBUG   SenderThread:335697 [sender.py:send():382] send: config
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: metric
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: telemetry
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: metric
2024-08-08 19:38:52,253 WARNING SenderThread:335697 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: telemetry
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: telemetry
2024-08-08 19:38:52,253 DEBUG   SenderThread:335697 [sender.py:send():382] send: config
2024-08-08 19:38:52,255 DEBUG   SenderThread:335697 [sender.py:send():382] send: exit
2024-08-08 19:38:52,255 INFO    SenderThread:335697 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 19:38:52,255 INFO    SenderThread:335697 [sender.py:send_exit():591] handling runtime: 1
2024-08-08 19:38:52,257 INFO    SenderThread:335697 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:38:52,257 INFO    SenderThread:335697 [sender.py:send_exit():597] send defer
2024-08-08 19:38:52,258 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,258 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 19:38:52,258 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,259 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 19:38:52,259 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 1
2024-08-08 19:38:52,259 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,259 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 19:38:52,259 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,259 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 19:38:52,259 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 2
2024-08-08 19:38:52,260 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,260 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 19:38:52,260 INFO    HandlerThread:335697 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 19:38:52,260 INFO    HandlerThread:335697 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 19:38:52,260 DEBUG   SystemMonitor:335697 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 19:38:52,261 DEBUG   SystemMonitor:335697 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 19:38:52,261 DEBUG   SystemMonitor:335697 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 19:38:52,262 INFO    HandlerThread:335697 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 19:38:52,291 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:38:52,291 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:52,291 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDE6FED7BB33</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [interfaces.py:finish():202] Joined network monitor
2024-08-08 19:38:52,297 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 3
2024-08-08 19:38:52,297 DEBUG   SenderThread:335697 [sender.py:send():382] send: stats
2024-08-08 19:38:52,297 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 19:38:52,297 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 4
2024-08-08 19:38:52,297 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 19:38:52,297 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 19:38:52,297 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 5
2024-08-08 19:38:52,297 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,297 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 19:38:52,298 DEBUG   SenderThread:335697 [sender.py:send():382] send: summary
2024-08-08 19:38:52,298 INFO    SenderThread:335697 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:38:52,298 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,298 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 19:38:52,298 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 6
2024-08-08 19:38:52,298 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,298 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 19:38:52,298 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,298 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 19:38:52,300 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 19:38:52,411 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 7
2024-08-08 19:38:52,411 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:52,411 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 19:38:52,411 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:52,411 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 19:38:52,507 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:38:52,507 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:52,507 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDE6FF81DEB1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:52,984 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:38:52,984 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:52,984 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDE727C5A441</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:53,137 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/config.yaml
2024-08-08 19:38:53,138 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/output.log
2024-08-08 19:38:53,138 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/wandb-summary.json
2024-08-08 19:38:53,212 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 19:38:53,524 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:38:53,525 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:53,525 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDE747FBE1A0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:53,824 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:38:53,824 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:53,824 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDE757C1CE6A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:53,825 INFO    wandb-upload_2:335697 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:38:54,232 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:38:54,232 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:54,232 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDE772275BC7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:54,268 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 8
2024-08-08 19:38:54,268 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 19:38:54,268 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:54,268 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 19:38:54,268 DEBUG   SenderThread:335697 [sender.py:send_request():409] send_request: defer
2024-08-08 19:38:54,268 INFO    SenderThread:335697 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 19:38:54,268 INFO    SenderThread:335697 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 19:38:54,269 INFO    SenderThread:335697 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 19:38:54,283 INFO    SenderThread:335697 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 19:38:54,295 INFO    SenderThread:335697 [sender.py:transition_state():617] send defer: 9
2024-08-08 19:38:54,295 DEBUG   SenderThread:335697 [sender.py:send():382] send: artifact
2024-08-08 19:38:54,295 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:38:54,297 INFO    HandlerThread:335697 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 19:38:55,138 INFO    Thread-12 :335697 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_193849-bvmwm3vs/files/output.log
2024-08-08 19:38:55,244 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:38:55,244 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:55,244 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDE7AED17292</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:55,337 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:38:55,337 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:55,337 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDE7AE990C56</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:55,600 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:38:55,600 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:55,601 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDE7C3BB38F7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:56,005 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:38:56,005 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:56,005 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDE7DA246180</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:56,327 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:38:56,327 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:56,327 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDE7EF07FA4D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:56,518 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:38:56,518 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:56,518 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDE7FAB0595D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:56,649 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:38:56,649 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:56,649 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDE801AE8CF9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:58,214 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:38:59,036 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:38:59,036 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:59,036 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDE89080EAFE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:59,036 INFO    wandb-upload_3:335697 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:38:59,555 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:38:59,555 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:38:59,555 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDE8973C6140</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:38:59,556 INFO    wandb-upload_4:335697 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:39:00,534 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:39:00,534 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:00,534 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDE8E9CF1A87</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:00,748 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:39:00,748 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:00,748 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDE8F50988D1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:01,287 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:39:01,287 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:01,287 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDE916B20EC9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:03,216 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:03,944 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:39:03,944 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:03,944 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDE9B33D0703</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:03,970 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:39:03,971 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:03,971 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDE9B6A903C2</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:08,218 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:08,866 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:39:08,866 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:08,866 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDEAD8DC0D7F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:09,773 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:39:09,774 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:09,774 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDEB1085CDA5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:09,899 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:39:09,899 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:09,899 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDEB17EB470D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:12,455 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:39:12,455 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:12,455 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDEBB04ECBDC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:13,220 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:13,611 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:39:13,611 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:13,611 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDEBF3B054D5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:18,222 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:23,224 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:25,999 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:39:25,999 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:25,999 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDEED5310324</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:27,454 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:39:27,454 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:27,454 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDEF24312F56</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:28,225 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:29,880 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:39:29,880 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:29,880 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDEFBEDE6618</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:30,743 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:39:30,744 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:30,744 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDEFF000072D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:32,150 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:39:32,151 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:32,151 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDF04663040E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:39:33,227 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:38,229 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:43,230 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:48,232 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:53,234 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:58,235 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:39:59,640 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f748974d07c56cd43ba5a41fa0a947c8b55a36087b7b97c9fcfab5aae04e901f
2024-08-08 19:39:59,640 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:39:59,641 ERROR   wandb-upload_1:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BDF6A8E026A3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:40:03,237 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:40:04,178 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=79341da33096aaa7b313a1d56f3ddb65995b4e6356a76989380964c2feb92a46
2024-08-08 19:40:04,179 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:40:04,179 ERROR   wandb-upload_0:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BDF7BB575FE1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:40:04,811 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/bvmwm3vs/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113852Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=77a9ced3b21b547eff3ebc7df6fd174993e2ccfab5ddc1c4e3f723fffc41e031
2024-08-08 19:40:04,811 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291731', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:40:04,811 ERROR   wandb-upload_2:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/bvmwm3vs/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/bvmwm3vs/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BDF7C6820F3D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:40:08,230 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=2b1aa80859b451213e6c5248950f8f2e086996140de3ca070897b556b3b3c10f
2024-08-08 19:40:08,230 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:40:08,230 ERROR   wandb-upload_3:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BDF8AD0B39C3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:40:08,239 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:40:10,278 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T113855Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=70a1fcecd6a80ba47433aedebf37e2122753150c99c702d3371633dc30c74db4
2024-08-08 19:40:10,279 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:40:10,279 ERROR   wandb-upload_4:335697 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/529/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BDF9246E9D2A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:40:13,241 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:40:18,242 DEBUG   HandlerThread:335697 [handler.py:handle_request():146] handle_request: keepalive
