2024-08-08 19:43:42,003 INFO    StreamThr :337205 [internal.py:wandb_internal():86] W&B internal server running at pid: 337205, started at: 2024-08-08 19:43:42.002956
2024-08-08 19:43:42,003 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: status
2024-08-08 19:43:42,004 INFO    WriterThread:337205 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/run-8eah3x4y.wandb
2024-08-08 19:43:42,004 DEBUG   SenderThread:337205 [sender.py:send():382] send: header
2024-08-08 19:43:42,038 DEBUG   SenderThread:337205 [sender.py:send():382] send: run
2024-08-08 19:43:42,280 INFO    SenderThread:337205 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files
2024-08-08 19:43:42,281 INFO    SenderThread:337205 [sender.py:_start_run_threads():1136] run started: 8eah3x4y with start time 1723117422.002913
2024-08-08 19:43:42,296 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 19:43:42,296 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: check_version
2024-08-08 19:43:42,399 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 19:43:42,407 DEBUG   HandlerThread:337205 [system_info.py:__init__():32] System info init
2024-08-08 19:43:42,407 DEBUG   HandlerThread:337205 [system_info.py:__init__():47] System info init done
2024-08-08 19:43:42,407 INFO    HandlerThread:337205 [system_monitor.py:start():194] Starting system monitor
2024-08-08 19:43:42,408 INFO    SystemMonitor:337205 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 19:43:42,408 INFO    HandlerThread:337205 [system_monitor.py:probe():214] Collecting system info
2024-08-08 19:43:42,408 INFO    SystemMonitor:337205 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 19:43:42,408 INFO    SystemMonitor:337205 [interfaces.py:start():190] Started disk monitoring
2024-08-08 19:43:42,409 INFO    SystemMonitor:337205 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 19:43:42,409 INFO    SystemMonitor:337205 [interfaces.py:start():190] Started memory monitoring
2024-08-08 19:43:42,409 INFO    SystemMonitor:337205 [interfaces.py:start():190] Started network monitoring
2024-08-08 19:43:42,414 DEBUG   HandlerThread:337205 [system_info.py:probe():196] Probing system
2024-08-08 19:43:42,416 DEBUG   HandlerThread:337205 [system_info.py:_probe_git():181] Probing git
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_info.py:_probe_git():189] Probing git done
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_info.py:probe():244] Probing system done
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T11:43:42.414945', 'startedAt': '2024-08-08T11:43:41.998162', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--use_lora', 'True', '--init_lora_weights', 'pissa_niter_4', '--target_modules', 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj', '--lora_rank', '32', '--lora_alpha', '32', '--lora_dropout', '0', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1482.77575, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 4716.146, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4749.059, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5480.074, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5414.758, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2734.221, 'min': 800.0, 'max': 5600.0}, {'current': 1231.893, 'min': 800.0, 'max': 5600.0}, {'current': 5491.886, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 5373.937, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5354.163, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 3679.388, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1099.59, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1175.559, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0419578552246}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 19:43:42,419 INFO    HandlerThread:337205 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 19:43:42,419 INFO    HandlerThread:337205 [system_monitor.py:probe():227] Publishing system info
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 19:43:42,419 DEBUG   HandlerThread:337205 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 19:43:43,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/requirements.txt
2024-08-08 19:43:43,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/conda-environment.yaml
2024-08-08 19:43:44,106 DEBUG   HandlerThread:337205 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 19:43:44,106 DEBUG   HandlerThread:337205 [system_info.py:_save_code():90] Saving code
2024-08-08 19:43:44,108 DEBUG   HandlerThread:337205 [system_info.py:_save_code():111] Saving code done
2024-08-08 19:43:44,108 DEBUG   HandlerThread:337205 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 19:43:44,147 DEBUG   HandlerThread:337205 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 19:43:44,148 INFO    HandlerThread:337205 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 19:43:44,151 DEBUG   SenderThread:337205 [sender.py:send():382] send: files
2024-08-08 19:43:44,151 INFO    SenderThread:337205 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 19:43:44,152 INFO    SenderThread:337205 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 19:43:44,153 INFO    SenderThread:337205 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 19:43:44,161 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 19:43:44,161 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 19:43:44,162 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: stop_status
2024-08-08 19:43:44,280 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/conda-environment.yaml
2024-08-08 19:43:44,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/code/llama/gmm.py
2024-08-08 19:43:44,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/diff.patch
2024-08-08 19:43:44,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/wandb-metadata.json
2024-08-08 19:43:44,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/code/llama
2024-08-08 19:43:44,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/code
2024-08-08 19:43:44,393 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:43:44,393 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:44,393 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE2B01362F7F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:44,423 DEBUG   SenderThread:337205 [sender.py:send():382] send: telemetry
2024-08-08 19:43:44,423 DEBUG   SenderThread:337205 [sender.py:send():382] send: config
2024-08-08 19:43:44,424 DEBUG   SenderThread:337205 [sender.py:send():382] send: metric
2024-08-08 19:43:44,424 DEBUG   SenderThread:337205 [sender.py:send():382] send: telemetry
2024-08-08 19:43:44,424 DEBUG   SenderThread:337205 [sender.py:send():382] send: metric
2024-08-08 19:43:44,424 WARNING SenderThread:337205 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 19:43:44,424 DEBUG   SenderThread:337205 [sender.py:send():382] send: telemetry
2024-08-08 19:43:44,425 DEBUG   SenderThread:337205 [sender.py:send():382] send: telemetry
2024-08-08 19:43:44,425 DEBUG   SenderThread:337205 [sender.py:send():382] send: config
2024-08-08 19:43:44,428 DEBUG   SenderThread:337205 [sender.py:send():382] send: exit
2024-08-08 19:43:44,428 INFO    SenderThread:337205 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 19:43:44,428 INFO    SenderThread:337205 [sender.py:send_exit():591] handling runtime: 1
2024-08-08 19:43:44,430 INFO    SenderThread:337205 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:43:44,430 INFO    SenderThread:337205 [sender.py:send_exit():597] send defer
2024-08-08 19:43:44,431 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,431 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 19:43:44,431 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,431 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 19:43:44,431 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 1
2024-08-08 19:43:44,432 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,432 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 19:43:44,432 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,432 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 19:43:44,432 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 2
2024-08-08 19:43:44,432 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,432 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 19:43:44,432 INFO    HandlerThread:337205 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 19:43:44,433 INFO    HandlerThread:337205 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 19:43:44,433 DEBUG   SystemMonitor:337205 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 19:43:44,433 DEBUG   SystemMonitor:337205 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 19:43:44,433 DEBUG   SystemMonitor:337205 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 19:43:44,435 INFO    HandlerThread:337205 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 19:43:44,476 INFO    HandlerThread:337205 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 19:43:44,476 INFO    HandlerThread:337205 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 19:43:44,476 INFO    HandlerThread:337205 [interfaces.py:finish():202] Joined network monitor
2024-08-08 19:43:44,476 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,476 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 19:43:44,476 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 3
2024-08-08 19:43:44,476 DEBUG   SenderThread:337205 [sender.py:send():382] send: stats
2024-08-08 19:43:44,476 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,476 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 19:43:44,476 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,476 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 19:43:44,476 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 4
2024-08-08 19:43:44,476 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,476 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 19:43:44,477 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 5
2024-08-08 19:43:44,477 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,477 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 19:43:44,477 DEBUG   SenderThread:337205 [sender.py:send():382] send: summary
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 19:43:44,477 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 6
2024-08-08 19:43:44,477 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,477 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 19:43:44,477 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,477 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 19:43:44,479 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 19:43:44,504 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:43:44,504 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:44,504 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE2B0474385E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:44,653 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 7
2024-08-08 19:43:44,654 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:44,654 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 19:43:44,654 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:44,654 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 19:43:45,079 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:43:45,079 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:45,079 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE2B09D7DCC9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:45,281 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/config.yaml
2024-08-08 19:43:45,282 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/wandb-summary.json
2024-08-08 19:43:45,282 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/output.log
2024-08-08 19:43:45,381 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 19:43:45,643 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:43:45,643 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:45,643 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE2B4679DFCA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:45,772 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:43:45,772 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:45,772 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE2B536C4FB7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:45,772 INFO    wandb-upload_1:337205 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:43:46,441 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 8
2024-08-08 19:43:46,441 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 19:43:46,442 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:46,442 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 19:43:46,442 DEBUG   SenderThread:337205 [sender.py:send_request():409] send_request: defer
2024-08-08 19:43:46,442 INFO    SenderThread:337205 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 19:43:46,442 INFO    SenderThread:337205 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 19:43:46,443 INFO    SenderThread:337205 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 19:43:46,457 INFO    SenderThread:337205 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 19:43:46,467 INFO    SenderThread:337205 [sender.py:transition_state():617] send defer: 9
2024-08-08 19:43:46,468 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: defer
2024-08-08 19:43:46,468 INFO    HandlerThread:337205 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 19:43:46,468 DEBUG   SenderThread:337205 [sender.py:send():382] send: artifact
2024-08-08 19:43:46,648 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:43:46,648 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:46,649 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE2B796CA7C6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:47,143 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:43:47,143 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:47,143 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE2BA51D42ED</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:47,264 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:43:47,265 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:47,265 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE2BA463A238</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:47,282 INFO    Thread-12 :337205 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_194341-8eah3x4y/files/output.log
2024-08-08 19:43:47,872 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:43:47,872 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:47,872 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE2BD0BFBC5C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:48,043 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:43:48,044 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:48,044 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE2BDAE36142</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:48,260 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:43:48,261 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:48,261 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE2BE7BB4FE0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:48,928 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:43:48,929 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:48,929 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE2C0560B04A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:49,029 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:43:49,029 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:49,029 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE2BF879DD24</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:50,384 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:43:50,697 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:43:50,697 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:50,697 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE2C78A23F3B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:50,697 INFO    wandb-upload_3:337205 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:43:51,172 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:43:51,173 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:51,173 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE2C93D5D6B5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:51,173 INFO    wandb-upload_4:337205 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 19:43:52,875 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:43:52,875 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:52,875 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE2CFAE74802</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:52,984 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:43:52,984 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:52,984 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE2CFC34284A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:53,516 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:43:53,516 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:53,517 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE2D0F588EBE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:55,386 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:43:55,491 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:43:55,491 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:55,491 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE2D82125042</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:43:55,671 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:43:55,672 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:43:55,672 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE2D9FF84F1E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:00,388 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:01,977 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:44:01,977 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:01,977 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE2F195EF88D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:02,359 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:44:02,359 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:02,359 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE2F3041A99D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:02,393 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:44:02,393 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:02,393 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE2F25955AB7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:05,086 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:44:05,086 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:05,086 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE2FD127B444</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:05,279 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:44:05,279 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:05,279 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE2FD8640D85</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:05,389 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:10,391 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:15,393 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:20,395 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:21,468 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=31a8a892823098474bd9273e3c5bbcbc358be5e422a562c34dd85956142f4c7e
2024-08-08 19:44:21,469 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:21,469 ERROR   wandb-upload_1:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BE339ED1DF1C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:22,343 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=3328f99af5542bf1d46e4dcec5c01c2406100a446cfcd47d724d896dd0bf4748
2024-08-08 19:44:22,344 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291736', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:22,344 ERROR   wandb-upload_2:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BE33B968DBFC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:22,364 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114344Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c6ba56e86749f08d1566c02bb3ac09b9689c60887979939d7d9e2c2187b07a28
2024-08-08 19:44:22,364 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5512', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:22,364 ERROR   wandb-upload_0:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/8eah3x4y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/8eah3x4y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BE33D88F232C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:22,895 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=afa77576aefcd2527af205e09cb44a5b5c3873b6894e05703f1a9368a6307468
2024-08-08 19:44:22,895 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:22,896 ERROR   wandb-upload_4:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9BE33F23A47BB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:23,405 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T114346Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=1ba244e5d8a1dcc4ab9191af7ed4ac986fab41abd4ead51f0b521eea24a593fd
2024-08-08 19:44:23,405 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 19:44:23,405 ERROR   wandb-upload_3:337205 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/530/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BE3416BD9143</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 19:44:25,397 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:30,399 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 19:44:35,401 DEBUG   HandlerThread:337205 [handler.py:handle_request():146] handle_request: keepalive
