2024-08-06 15:59:38,737 INFO    StreamThr :2045039 [internal.py:wandb_internal():86] W&B internal server running at pid: 2045039, started at: 2024-08-06 15:59:38.737311
2024-08-06 15:59:38,738 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status
2024-08-06 15:59:38,739 INFO    WriterThread:2045039 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/run-y6h0adoc.wandb
2024-08-06 15:59:38,739 DEBUG   SenderThread:2045039 [sender.py:send():382] send: header
2024-08-06 15:59:38,739 DEBUG   SenderThread:2045039 [sender.py:send():382] send: run
2024-08-06 15:59:38,964 INFO    SenderThread:2045039 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files
2024-08-06 15:59:38,964 INFO    SenderThread:2045039 [sender.py:_start_run_threads():1136] run started: y6h0adoc with start time 1722931178.737206
2024-08-06 15:59:38,971 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 15:59:38,971 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: check_version
2024-08-06 15:59:39,080 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 15:59:39,084 DEBUG   HandlerThread:2045039 [system_info.py:__init__():32] System info init
2024-08-06 15:59:39,084 DEBUG   HandlerThread:2045039 [system_info.py:__init__():47] System info init done
2024-08-06 15:59:39,084 INFO    HandlerThread:2045039 [system_monitor.py:start():194] Starting system monitor
2024-08-06 15:59:39,084 INFO    SystemMonitor:2045039 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 15:59:39,084 INFO    HandlerThread:2045039 [system_monitor.py:probe():214] Collecting system info
2024-08-06 15:59:39,084 INFO    SystemMonitor:2045039 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 15:59:39,085 INFO    SystemMonitor:2045039 [interfaces.py:start():190] Started disk monitoring
2024-08-06 15:59:39,085 INFO    SystemMonitor:2045039 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 15:59:39,085 INFO    SystemMonitor:2045039 [interfaces.py:start():190] Started memory monitoring
2024-08-06 15:59:39,086 INFO    SystemMonitor:2045039 [interfaces.py:start():190] Started network monitoring
2024-08-06 15:59:39,094 DEBUG   HandlerThread:2045039 [system_info.py:probe():196] Probing system
2024-08-06 15:59:39,095 DEBUG   HandlerThread:2045039 [system_info.py:_probe_git():181] Probing git
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_info.py:_probe_git():189] Probing git done
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_info.py:probe():244] Probing system done
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T07:59:39.094474', 'startedAt': '2024-08-06T07:59:38.732723', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2b', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 2222.8243214285712, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5499.781, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 5420.425, 'min': 800.0, 'max': 5600.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5500.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 2785.065, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1133.81, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 439.2187728881836}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 15:59:39,098 INFO    HandlerThread:2045039 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 15:59:39,098 INFO    HandlerThread:2045039 [system_monitor.py:probe():227] Publishing system info
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 15:59:39,098 DEBUG   HandlerThread:2045039 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 15:59:39,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/requirements.txt
2024-08-06 15:59:39,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/conda-environment.yaml
2024-08-06 15:59:40,774 DEBUG   HandlerThread:2045039 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 15:59:40,774 DEBUG   HandlerThread:2045039 [system_info.py:_save_code():90] Saving code
2024-08-06 15:59:40,775 DEBUG   HandlerThread:2045039 [system_info.py:_save_code():111] Saving code done
2024-08-06 15:59:40,775 DEBUG   HandlerThread:2045039 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 15:59:40,778 ERROR   HandlerThread:2045039 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 15:59:40,778 DEBUG   HandlerThread:2045039 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 15:59:40,778 INFO    HandlerThread:2045039 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 15:59:40,779 DEBUG   SenderThread:2045039 [sender.py:send():382] send: files
2024-08-06 15:59:40,779 INFO    SenderThread:2045039 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 15:59:40,780 INFO    SenderThread:2045039 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 15:59:40,782 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 15:59:40,782 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 15:59:40,782 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: stop_status
2024-08-06 15:59:40,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/conda-environment.yaml
2024-08-06 15:59:40,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/wandb-metadata.json
2024-08-06 15:59:40,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/code/llama/gmm.py
2024-08-06 15:59:40,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/code
2024-08-06 15:59:40,964 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/code/llama
2024-08-06 15:59:41,028 DEBUG   SenderThread:2045039 [sender.py:send():382] send: telemetry
2024-08-06 15:59:41,028 DEBUG   SenderThread:2045039 [sender.py:send():382] send: config
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: metric
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: telemetry
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: metric
2024-08-06 15:59:41,030 WARNING SenderThread:2045039 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: telemetry
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: telemetry
2024-08-06 15:59:41,030 DEBUG   SenderThread:2045039 [sender.py:send():382] send: config
2024-08-06 15:59:41,033 DEBUG   SenderThread:2045039 [sender.py:send():382] send: exit
2024-08-06 15:59:41,033 INFO    SenderThread:2045039 [sender.py:send_exit():589] handling exit code: 1
2024-08-06 15:59:41,033 INFO    SenderThread:2045039 [sender.py:send_exit():591] handling runtime: 1
2024-08-06 15:59:41,035 INFO    SenderThread:2045039 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:59:41,036 INFO    SenderThread:2045039 [sender.py:send_exit():597] send defer
2024-08-06 15:59:41,036 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,036 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-06 15:59:41,037 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,037 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-06 15:59:41,037 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 1
2024-08-06 15:59:41,037 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,037 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-06 15:59:41,038 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,038 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-06 15:59:41,038 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 2
2024-08-06 15:59:41,038 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,038 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-06 15:59:41,038 INFO    HandlerThread:2045039 [system_monitor.py:finish():203] Stopping system monitor
2024-08-06 15:59:41,038 DEBUG   SystemMonitor:2045039 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-06 15:59:41,039 DEBUG   SystemMonitor:2045039 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-06 15:59:41,039 DEBUG   SystemMonitor:2045039 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-06 15:59:41,040 INFO    HandlerThread:2045039 [interfaces.py:finish():202] Joined cpu monitor
2024-08-06 15:59:41,040 INFO    HandlerThread:2045039 [interfaces.py:finish():202] Joined disk monitor
2024-08-06 15:59:41,098 INFO    HandlerThread:2045039 [interfaces.py:finish():202] Joined gpu monitor
2024-08-06 15:59:41,099 INFO    HandlerThread:2045039 [interfaces.py:finish():202] Joined memory monitor
2024-08-06 15:59:41,099 INFO    HandlerThread:2045039 [interfaces.py:finish():202] Joined network monitor
2024-08-06 15:59:41,099 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 3
2024-08-06 15:59:41,099 DEBUG   SenderThread:2045039 [sender.py:send():382] send: stats
2024-08-06 15:59:41,099 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,099 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-06 15:59:41,099 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 4
2024-08-06 15:59:41,099 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,099 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-06 15:59:41,099 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 5
2024-08-06 15:59:41,099 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,099 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-06 15:59:41,099 DEBUG   SenderThread:2045039 [sender.py:send():382] send: summary
2024-08-06 15:59:41,099 INFO    SenderThread:2045039 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 15:59:41,100 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,100 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-06 15:59:41,100 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 6
2024-08-06 15:59:41,100 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,100 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-06 15:59:41,100 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,100 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-06 15:59:41,101 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:59:41,294 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 7
2024-08-06 15:59:41,294 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:41,294 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-06 15:59:41,295 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:41,295 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-06 15:59:41,424 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a
2024-08-06 15:59:41,424 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5164', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:41,424 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914C7EECCD244</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:41,960 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-06 15:59:41,965 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/config.yaml
2024-08-06 15:59:41,965 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/wandb-summary.json
2024-08-06 15:59:41,966 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/output.log
2024-08-06 15:59:42,496 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a
2024-08-06 15:59:42,496 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5164', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:42,496 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914C82EB1966B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:43,045 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 8
2024-08-06 15:59:43,045 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: poll_exit
2024-08-06 15:59:43,045 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:43,045 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-06 15:59:43,046 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [job_builder.py:build():298] Attempting to build job artifact
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [job_builder.py:_get_source_type():439] no source found
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 9
2024-08-06 15:59:43,046 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:43,046 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-06 15:59:43,046 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 9
2024-08-06 15:59:43,046 INFO    SenderThread:2045039 [dir_watcher.py:finish():358] shutting down directory watcher
2024-08-06 15:59:43,966 INFO    Thread-12 :2045039 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/output.log
2024-08-06 15:59:43,967 INFO    SenderThread:2045039 [dir_watcher.py:finish():388] scan: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files
2024-08-06 15:59:43,968 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/wandb-summary.json wandb-summary.json
2024-08-06 15:59:43,968 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/requirements.txt requirements.txt
2024-08-06 15:59:43,968 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/output.log output.log
2024-08-06 15:59:43,973 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/config.yaml config.yaml
2024-08-06 15:59:43,977 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/wandb-metadata.json wandb-metadata.json
2024-08-06 15:59:43,977 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/conda-environment.yaml conda-environment.yaml
2024-08-06 15:59:43,978 INFO    SenderThread:2045039 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/code/llama/gmm.py code/llama/gmm.py
2024-08-06 15:59:43,979 INFO    SenderThread:2045039 [sender.py:transition_state():617] send defer: 10
2024-08-06 15:59:43,979 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: defer
2024-08-06 15:59:43,979 INFO    HandlerThread:2045039 [handler.py:handle_request_defer():172] handle defer: 10
2024-08-06 15:59:43,983 DEBUG   SenderThread:2045039 [sender.py:send_request():409] send_request: defer
2024-08-06 15:59:43,986 INFO    SenderThread:2045039 [sender.py:send_request_defer():613] handle sender defer: 10
2024-08-06 15:59:43,986 INFO    SenderThread:2045039 [file_pusher.py:finish():175] shutting down file pusher
2024-08-06 15:59:44,095 INFO    wandb-upload_2:2045039 [upload_job.py:push():131] Uploaded file /home/rwkv/JL/GMM/llama/wandb/run-20240806_155938-y6h0adoc/files/wandb-summary.json
2024-08-06 15:59:44,178 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b
2024-08-06 15:59:44,178 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8377', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:44,178 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/output.log</Resource><Region>wandb-local</Region><RequestId>17E914C892A5B8D2</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:44,298 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4
2024-08-06 15:59:44,298 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:44,298 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E914C89A27993B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:44,466 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c
2024-08-06 15:59:44,466 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:44,466 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E914C89405A192</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:44,773 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a
2024-08-06 15:59:44,773 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5164', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:44,773 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914C8B697CDD6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:45,280 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b
2024-08-06 15:59:45,280 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8377', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:45,280 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/output.log</Resource><Region>wandb-local</Region><RequestId>17E914C8D4375F71</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:45,280 INFO    wandb-upload_4:2045039 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 15:59:45,566 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4
2024-08-06 15:59:45,567 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:45,567 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E914C8E507355B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:45,746 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c
2024-08-06 15:59:45,746 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:45,746 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E914C8F0515701</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:46,962 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 15:59:47,825 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b
2024-08-06 15:59:47,825 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8377', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:47,825 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/output.log</Resource><Region>wandb-local</Region><RequestId>17E914C96BFA813A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:47,837 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4
2024-08-06 15:59:47,837 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:47,837 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E914C96C2906F4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:47,865 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c
2024-08-06 15:59:47,865 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:47,865 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E914C96E7628BB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:48,868 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a
2024-08-06 15:59:48,869 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5164', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:48,869 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914C9AA624152</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:48,987 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:59:51,920 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c
2024-08-06 15:59:51,920 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:51,920 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E914CA60438D31</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:51,964 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 15:59:51,991 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b
2024-08-06 15:59:51,992 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8377', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:51,992 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/output.log</Resource><Region>wandb-local</Region><RequestId>17E914CA645FF1CC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:52,129 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4
2024-08-06 15:59:52,129 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:52,129 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E914CA6804D93D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:53,988 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 15:59:56,966 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 15:59:57,250 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075941Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=679cc9de7084a718171c6731211f3997b366bfe4c71b115db2a2f7ca6acd352a
2024-08-06 15:59:57,250 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5164', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 15:59:57,250 ERROR   wandb-upload_0:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E914CB9DD81707</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 15:59:58,989 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 16:00:00,423 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=0593f00ebf612e0134425cd9276584f0dd41bc8e7a434c28dc6c464284df6b2b
2024-08-06 16:00:00,423 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8377', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:00,423 ERROR   wandb-upload_4:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/output.log</Resource><Region>wandb-local</Region><RequestId>17E914CC5640E83C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:00,763 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1b015d670fe60574d11de8a26daa24db9531ac76773518d256110b773e167af4
2024-08-06 16:00:00,764 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:00,764 ERROR   wandb-upload_6:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E914CC6F0FAA07</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:00,809 INFO    wandb-upload_1:2045039 [upload_job.py:push():131] Uploaded file /tmp/tmpk76no45rwandb/3loffhoq-code/llama/gmm.py
2024-08-06 16:00:01,602 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c
2024-08-06 16:00:01,602 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:01,602 ERROR   wandb-upload_3:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E914CCA13F85FE</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:01,603 INFO    wandb-upload_3:2045039 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T075944Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d14853c934cdf2433d9614a5a9810c87d38d2e9e47eda6f2ade7f72ecad8343c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 16:00:01,968 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 16:00:03,990 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 16:00:05,377 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745
2024-08-06 16:00:05,377 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11174', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:05,377 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E914CD81EF25B5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:06,800 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745
2024-08-06 16:00:06,800 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11174', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:06,800 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E914CDCF806AEF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:06,969 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 16:00:08,990 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 16:00:09,838 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745
2024-08-06 16:00:09,839 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11174', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 16:00:09,839 ERROR   wandb-upload_5:2045039 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/y6h0adoc/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/y6h0adoc/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E914CE6F33CF61</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 16:00:09,839 INFO    wandb-upload_5:2045039 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/y6h0adoc/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T080005Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=222bb48d2e8e6d218aab866c0aef203309bf80d41283f04327bff686a4a1c745

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 16:00:11,971 DEBUG   HandlerThread:2045039 [handler.py:handle_request():146] handle_request: keepalive
