2024-08-06 19:31:22,322 INFO    StreamThr :2131756 [internal.py:wandb_internal():86] W&B internal server running at pid: 2131756, started at: 2024-08-06 19:31:22.321667
2024-08-06 19:31:22,325 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: status
2024-08-06 19:31:22,329 INFO    WriterThread:2131756 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/run-u0co65sn.wandb
2024-08-06 19:31:22,330 DEBUG   SenderThread:2131756 [sender.py:send():382] send: header
2024-08-06 19:31:22,330 DEBUG   SenderThread:2131756 [sender.py:send():382] send: run
2024-08-06 19:31:22,490 INFO    SenderThread:2131756 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files
2024-08-06 19:31:22,490 INFO    SenderThread:2131756 [sender.py:_start_run_threads():1136] run started: u0co65sn with start time 1722943882.321571
2024-08-06 19:31:22,504 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 19:31:22,505 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: check_version
2024-08-06 19:31:22,633 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 19:31:22,648 DEBUG   HandlerThread:2131756 [system_info.py:__init__():32] System info init
2024-08-06 19:31:22,648 DEBUG   HandlerThread:2131756 [system_info.py:__init__():47] System info init done
2024-08-06 19:31:22,649 INFO    HandlerThread:2131756 [system_monitor.py:start():194] Starting system monitor
2024-08-06 19:31:22,649 INFO    SystemMonitor:2131756 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 19:31:22,649 INFO    HandlerThread:2131756 [system_monitor.py:probe():214] Collecting system info
2024-08-06 19:31:22,649 INFO    SystemMonitor:2131756 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 19:31:22,650 INFO    SystemMonitor:2131756 [interfaces.py:start():190] Started disk monitoring
2024-08-06 19:31:22,651 INFO    SystemMonitor:2131756 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 19:31:22,651 INFO    SystemMonitor:2131756 [interfaces.py:start():190] Started memory monitoring
2024-08-06 19:31:22,652 INFO    SystemMonitor:2131756 [interfaces.py:start():190] Started network monitoring
2024-08-06 19:31:22,657 DEBUG   HandlerThread:2131756 [system_info.py:probe():196] Probing system
2024-08-06 19:31:22,658 DEBUG   HandlerThread:2131756 [system_info.py:_probe_git():181] Probing git
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_info.py:_probe_git():189] Probing git done
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_info.py:probe():244] Probing system done
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T11:31:22.657402', 'startedAt': '2024-08-06T11:31:22.309055', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--use_lora', 'True', '--init_lora_weights', 'True', '--target_modules', 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj', '--lora_rank', '32', '--lora_alpha', '32', '--lora_dropout', '0', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1591.7111071428571, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 2442.053, 'min': 800.0, 'max': 5500.0}, {'current': 1761.911, 'min': 800.0, 'max': 5500.0}, {'current': 2502.714, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2641.687, 'min': 800.0, 'max': 5500.0}, {'current': 3541.485, 'min': 800.0, 'max': 5500.0}, {'current': 2773.718, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1185.896, 'min': 800.0, 'max': 5600.0}, {'current': 2270.453, 'min': 800.0, 'max': 5600.0}, {'current': 2751.296, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2271.275, 'min': 800.0, 'max': 5500.0}, {'current': 2694.362, 'min': 800.0, 'max': 5500.0}, {'current': 1682.025, 'min': 800.0, 'max': 5500.0}, {'current': 2404.963, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 2145.454, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1098.619, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.3694839477539}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 19:31:22,659 INFO    HandlerThread:2131756 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 19:31:22,659 INFO    HandlerThread:2131756 [system_monitor.py:probe():227] Publishing system info
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 19:31:22,659 DEBUG   HandlerThread:2131756 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 19:31:23,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/requirements.txt
2024-08-06 19:31:23,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/conda-environment.yaml
2024-08-06 19:31:24,336 DEBUG   HandlerThread:2131756 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 19:31:24,337 DEBUG   HandlerThread:2131756 [system_info.py:_save_code():90] Saving code
2024-08-06 19:31:24,338 DEBUG   HandlerThread:2131756 [system_info.py:_save_code():111] Saving code done
2024-08-06 19:31:24,338 DEBUG   HandlerThread:2131756 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 19:31:24,341 ERROR   HandlerThread:2131756 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 19:31:24,341 DEBUG   HandlerThread:2131756 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 19:31:24,341 INFO    HandlerThread:2131756 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 19:31:24,342 DEBUG   SenderThread:2131756 [sender.py:send():382] send: files
2024-08-06 19:31:24,342 INFO    SenderThread:2131756 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 19:31:24,342 INFO    SenderThread:2131756 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 19:31:24,344 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:31:24,345 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:31:24,345 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:31:24,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/conda-environment.yaml
2024-08-06 19:31:24,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/wandb-metadata.json
2024-08-06 19:31:24,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/code/llama/gmm.py
2024-08-06 19:31:24,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/code
2024-08-06 19:31:24,490 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/code/llama
2024-08-06 19:31:24,580 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e
2024-08-06 19:31:24,580 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5488', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:24,580 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E920559EB62E46</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:24,679 DEBUG   SenderThread:2131756 [sender.py:send():382] send: telemetry
2024-08-06 19:31:24,679 DEBUG   SenderThread:2131756 [sender.py:send():382] send: config
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: metric
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: telemetry
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: metric
2024-08-06 19:31:24,681 WARNING SenderThread:2131756 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: telemetry
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: telemetry
2024-08-06 19:31:24,681 DEBUG   SenderThread:2131756 [sender.py:send():382] send: config
2024-08-06 19:31:24,684 DEBUG   SenderThread:2131756 [sender.py:send():382] send: exit
2024-08-06 19:31:24,684 INFO    SenderThread:2131756 [sender.py:send_exit():589] handling exit code: 1
2024-08-06 19:31:24,684 INFO    SenderThread:2131756 [sender.py:send_exit():591] handling runtime: 1
2024-08-06 19:31:24,687 INFO    SenderThread:2131756 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:31:24,687 INFO    SenderThread:2131756 [sender.py:send_exit():597] send defer
2024-08-06 19:31:24,687 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,688 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-06 19:31:24,688 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,688 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-06 19:31:24,688 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 1
2024-08-06 19:31:24,689 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,689 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-06 19:31:24,689 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,689 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-06 19:31:24,689 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 2
2024-08-06 19:31:24,690 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,690 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-06 19:31:24,690 INFO    HandlerThread:2131756 [system_monitor.py:finish():203] Stopping system monitor
2024-08-06 19:31:24,690 DEBUG   SystemMonitor:2131756 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-06 19:31:24,691 DEBUG   SystemMonitor:2131756 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-06 19:31:24,691 DEBUG   SystemMonitor:2131756 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-06 19:31:24,692 INFO    HandlerThread:2131756 [interfaces.py:finish():202] Joined cpu monitor
2024-08-06 19:31:24,693 INFO    HandlerThread:2131756 [interfaces.py:finish():202] Joined disk monitor
2024-08-06 19:31:24,775 INFO    HandlerThread:2131756 [interfaces.py:finish():202] Joined gpu monitor
2024-08-06 19:31:24,775 INFO    HandlerThread:2131756 [interfaces.py:finish():202] Joined memory monitor
2024-08-06 19:31:24,775 INFO    HandlerThread:2131756 [interfaces.py:finish():202] Joined network monitor
2024-08-06 19:31:24,775 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,775 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-06 19:31:24,775 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 3
2024-08-06 19:31:24,775 DEBUG   SenderThread:2131756 [sender.py:send():382] send: stats
2024-08-06 19:31:24,775 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,775 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-06 19:31:24,776 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 4
2024-08-06 19:31:24,776 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,776 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-06 19:31:24,776 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 5
2024-08-06 19:31:24,776 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,776 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-06 19:31:24,776 DEBUG   SenderThread:2131756 [sender.py:send():382] send: summary
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:31:24,776 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-06 19:31:24,776 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 6
2024-08-06 19:31:24,777 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,777 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-06 19:31:24,777 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,777 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-06 19:31:24,778 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:31:24,780 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2
2024-08-06 19:31:24,781 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:24,781 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E92055A679AB92</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:24,938 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 7
2024-08-06 19:31:24,938 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:24,938 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-06 19:31:24,938 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:24,938 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-06 19:31:25,491 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/config.yaml
2024-08-06 19:31:25,491 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/output.log
2024-08-06 19:31:25,492 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/wandb-summary.json
2024-08-06 19:31:25,591 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-06 19:31:25,863 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e
2024-08-06 19:31:25,863 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5488', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:25,864 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E92055EAE44736</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:26,048 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2
2024-08-06 19:31:26,048 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:26,048 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E92055F5079E97</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:26,049 INFO    wandb-upload_1:2131756 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:31:26,697 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 8
2024-08-06 19:31:26,698 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: poll_exit
2024-08-06 19:31:26,698 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:26,698 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-06 19:31:26,699 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:26,699 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-06 19:31:26,699 INFO    SenderThread:2131756 [job_builder.py:build():298] Attempting to build job artifact
2024-08-06 19:31:26,699 INFO    SenderThread:2131756 [job_builder.py:_get_source_type():439] no source found
2024-08-06 19:31:26,699 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 9
2024-08-06 19:31:26,699 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:26,699 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-06 19:31:26,699 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:26,699 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 9
2024-08-06 19:31:26,700 INFO    SenderThread:2131756 [dir_watcher.py:finish():358] shutting down directory watcher
2024-08-06 19:31:27,492 INFO    Thread-12 :2131756 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/output.log
2024-08-06 19:31:27,493 INFO    SenderThread:2131756 [dir_watcher.py:finish():388] scan: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files
2024-08-06 19:31:27,493 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/wandb-summary.json wandb-summary.json
2024-08-06 19:31:27,494 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/requirements.txt requirements.txt
2024-08-06 19:31:27,494 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/output.log output.log
2024-08-06 19:31:27,494 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/config.yaml config.yaml
2024-08-06 19:31:27,494 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/wandb-metadata.json wandb-metadata.json
2024-08-06 19:31:27,494 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/conda-environment.yaml conda-environment.yaml
2024-08-06 19:31:27,514 INFO    SenderThread:2131756 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/code/llama/gmm.py code/llama/gmm.py
2024-08-06 19:31:27,514 INFO    SenderThread:2131756 [sender.py:transition_state():617] send defer: 10
2024-08-06 19:31:27,514 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: defer
2024-08-06 19:31:27,515 INFO    HandlerThread:2131756 [handler.py:handle_request_defer():172] handle defer: 10
2024-08-06 19:31:27,515 DEBUG   SenderThread:2131756 [sender.py:send_request():409] send_request: defer
2024-08-06 19:31:27,515 INFO    SenderThread:2131756 [sender.py:send_request_defer():613] handle sender defer: 10
2024-08-06 19:31:27,516 INFO    SenderThread:2131756 [file_pusher.py:finish():175] shutting down file pusher
2024-08-06 19:31:27,651 INFO    wandb-upload_2:2131756 [upload_job.py:push():131] Uploaded file /home/rwkv/JL/GMM/llama/wandb/run-20240806_193122-u0co65sn/files/wandb-summary.json
2024-08-06 19:31:27,747 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad
2024-08-06 19:31:27,747 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11807', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:27,747 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/output.log</Resource><Region>wandb-local</Region><RequestId>17E9205654890482</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:27,815 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e
2024-08-06 19:31:27,815 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:27,815 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E920565F7FE804</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:27,827 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2
2024-08-06 19:31:27,827 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:27,827 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E92056603370F0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:28,094 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24
2024-08-06 19:31:28,094 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '12039', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:28,095 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E920565F6066ED</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:28,312 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e
2024-08-06 19:31:28,312 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5488', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:28,312 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9205677C524A3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:28,312 INFO    wandb-upload_0:2131756 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:31:28,453 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2
2024-08-06 19:31:28,453 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:28,453 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9205684E81963</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:28,453 INFO    wandb-upload_1:2131756 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:31:29,020 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad
2024-08-06 19:31:29,020 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11807', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:29,021 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/output.log</Resource><Region>wandb-local</Region><RequestId>17E92056A1C56003</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:29,043 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2
2024-08-06 19:31:29,043 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:29,043 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E92056A89324DF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:29,156 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e
2024-08-06 19:31:29,156 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:29,156 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E92056AEA79CA5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:29,337 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24
2024-08-06 19:31:29,337 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '12039', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:29,338 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E92056B9324C20</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:30,593 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: keepalive
2024-08-06 19:31:31,171 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=fa0fde810912a1d1220a085fd82cc589c336660dbb9a067554ab1b9ccdffacd2
2024-08-06 19:31:31,171 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:31,171 ERROR   wandb-upload_3:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E9205727678FAA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:31,214 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f7ca8514710de8edec6b0bf22cf055cb6d984119ecbbf30d6e79e8c1f9cacaad
2024-08-06 19:31:31,214 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11807', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:31,214 ERROR   wandb-upload_4:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/output.log</Resource><Region>wandb-local</Region><RequestId>17E9205728DAB572</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:31,442 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=f3e6ebf108da583a9c51352b88cc0d626f6eeb83adf5fa0f77acd305c2a16b24
2024-08-06 19:31:31,443 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '12039', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:31,443 ERROR   wandb-upload_5:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E9205736BE223E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:31,467 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113127Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c3de86d7d0e0d4069980fd54bf24201b1cbaab52e88505819cb314375645103e
2024-08-06 19:31:31,468 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:31,468 ERROR   wandb-upload_6:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E92057341872E9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:32,517 DEBUG   HandlerThread:2131756 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:31:33,010 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=450e7069e399cf4391de52a297684efd7ab1efa77381f5c4c3888965c49aede2
2024-08-06 19:31:33,010 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:33,010 ERROR   wandb-upload_1:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E920577DE067B4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:31:33,292 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T113124Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=65798bd0f761f81636ab4e12d01e35fe28cb94980e76af1cc56773f5ef96472e
2024-08-06 19:31:33,292 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5488', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:31:33,292 ERROR   wandb-upload_0:2131756 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/u0co65sn/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/u0co65sn/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E92057A414E60B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
