2024-08-07 18:37:00,256 INFO    StreamThr :31357 [internal.py:wandb_internal():86] W&B internal server running at pid: 31357, started at: 2024-08-07 18:37:00.256242
2024-08-07 18:37:00,257 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: status
2024-08-07 18:37:00,259 INFO    WriterThread:31357 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/run-pm4133ad.wandb
2024-08-07 18:37:00,259 DEBUG   SenderThread:31357 [sender.py:send():382] send: header
2024-08-07 18:37:00,282 DEBUG   SenderThread:31357 [sender.py:send():382] send: run
2024-08-07 18:37:00,533 INFO    SenderThread:31357 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files
2024-08-07 18:37:00,533 INFO    SenderThread:31357 [sender.py:_start_run_threads():1136] run started: pm4133ad with start time 1723027020.256207
2024-08-07 18:37:00,545 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: check_version
2024-08-07 18:37:00,545 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: check_version
2024-08-07 18:37:00,654 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: run_start
2024-08-07 18:37:00,670 DEBUG   HandlerThread:31357 [system_info.py:__init__():32] System info init
2024-08-07 18:37:00,670 DEBUG   HandlerThread:31357 [system_info.py:__init__():47] System info init done
2024-08-07 18:37:00,670 INFO    HandlerThread:31357 [system_monitor.py:start():194] Starting system monitor
2024-08-07 18:37:00,670 INFO    SystemMonitor:31357 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-07 18:37:00,670 INFO    HandlerThread:31357 [system_monitor.py:probe():214] Collecting system info
2024-08-07 18:37:00,671 INFO    SystemMonitor:31357 [interfaces.py:start():190] Started cpu monitoring
2024-08-07 18:37:00,674 INFO    SystemMonitor:31357 [interfaces.py:start():190] Started disk monitoring
2024-08-07 18:37:00,675 INFO    SystemMonitor:31357 [interfaces.py:start():190] Started gpu monitoring
2024-08-07 18:37:00,676 INFO    SystemMonitor:31357 [interfaces.py:start():190] Started memory monitoring
2024-08-07 18:37:00,677 INFO    SystemMonitor:31357 [interfaces.py:start():190] Started network monitoring
2024-08-07 18:37:00,688 DEBUG   HandlerThread:31357 [system_info.py:probe():196] Probing system
2024-08-07 18:37:00,689 DEBUG   HandlerThread:31357 [system_info.py:_probe_git():181] Probing git
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_info.py:_probe_git():189] Probing git done
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_info.py:probe():244] Probing system done
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-07T10:37:00.688428', 'startedAt': '2024-08-07T10:37:00.251057', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1017.9675357142858, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1231.53, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1235.197, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1491.582, 'min': 800.0, 'max': 5500.0}, {'current': 1277.173, 'min': 800.0, 'max': 5500.0}, {'current': 1246.689, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1392.126, 'min': 800.0, 'max': 5600.0}, {'current': 1242.403, 'min': 800.0, 'max': 5600.0}, {'current': 1402.576, 'min': 800.0, 'max': 5600.0}, {'current': 1636.147, 'min': 800.0, 'max': 5600.0}, {'current': 1438.968, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1507.152, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1498.78, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1369.464, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 474.6812858581543}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-07 18:37:00,692 INFO    HandlerThread:31357 [system_monitor.py:probe():224] Finished collecting system info
2024-08-07 18:37:00,692 INFO    HandlerThread:31357 [system_monitor.py:probe():227] Publishing system info
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-07 18:37:00,692 DEBUG   HandlerThread:31357 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-07 18:37:01,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/requirements.txt
2024-08-07 18:37:01,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/conda-environment.yaml
2024-08-07 18:37:02,373 DEBUG   HandlerThread:31357 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-07 18:37:02,373 DEBUG   HandlerThread:31357 [system_info.py:_save_code():90] Saving code
2024-08-07 18:37:02,374 DEBUG   HandlerThread:31357 [system_info.py:_save_code():111] Saving code done
2024-08-07 18:37:02,374 DEBUG   HandlerThread:31357 [system_info.py:_save_patches():128] Saving git patches
2024-08-07 18:37:02,413 DEBUG   HandlerThread:31357 [system_info.py:_save_patches():170] Saving git patches done
2024-08-07 18:37:02,413 INFO    HandlerThread:31357 [system_monitor.py:probe():229] Finished publishing system info
2024-08-07 18:37:02,415 DEBUG   SenderThread:31357 [sender.py:send():382] send: files
2024-08-07 18:37:02,415 INFO    SenderThread:31357 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-07 18:37:02,416 INFO    SenderThread:31357 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-07 18:37:02,416 INFO    SenderThread:31357 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-07 18:37:02,422 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: stop_status
2024-08-07 18:37:02,422 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: stop_status
2024-08-07 18:37:02,424 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/conda-environment.yaml
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/wandb-metadata.json
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/code/llama/gmm.py
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/diff.patch
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/code
2024-08-07 18:37:02,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/code/llama
2024-08-07 18:37:02,654 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d
2024-08-07 18:37:02,654 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5219', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:02,654 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96BF2B7EA7F3A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:02,675 DEBUG   SenderThread:31357 [sender.py:send():382] send: telemetry
2024-08-07 18:37:02,675 DEBUG   SenderThread:31357 [sender.py:send():382] send: config
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: metric
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: telemetry
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: metric
2024-08-07 18:37:02,676 WARNING SenderThread:31357 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: telemetry
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: telemetry
2024-08-07 18:37:02,676 DEBUG   SenderThread:31357 [sender.py:send():382] send: config
2024-08-07 18:37:02,768 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86
2024-08-07 18:37:02,768 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:02,768 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96BF2BB03DDB8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:02,801 DEBUG   SenderThread:31357 [sender.py:send():382] send: exit
2024-08-07 18:37:02,801 INFO    SenderThread:31357 [sender.py:send_exit():589] handling exit code: 1
2024-08-07 18:37:02,801 INFO    SenderThread:31357 [sender.py:send_exit():591] handling runtime: 2
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:send_exit():597] send defer
2024-08-07 18:37:02,802 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,802 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-07 18:37:02,802 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 1
2024-08-07 18:37:02,802 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,802 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-07 18:37:02,802 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-07 18:37:02,802 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 2
2024-08-07 18:37:02,802 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,802 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-07 18:37:02,802 INFO    HandlerThread:31357 [system_monitor.py:finish():203] Stopping system monitor
2024-08-07 18:37:02,802 DEBUG   SystemMonitor:31357 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-07 18:37:02,802 DEBUG   SystemMonitor:31357 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-07 18:37:02,802 DEBUG   SystemMonitor:31357 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-07 18:37:02,803 INFO    HandlerThread:31357 [interfaces.py:finish():202] Joined cpu monitor
2024-08-07 18:37:02,803 INFO    HandlerThread:31357 [interfaces.py:finish():202] Joined disk monitor
2024-08-07 18:37:02,822 INFO    HandlerThread:31357 [interfaces.py:finish():202] Joined gpu monitor
2024-08-07 18:37:02,822 INFO    HandlerThread:31357 [interfaces.py:finish():202] Joined memory monitor
2024-08-07 18:37:02,822 INFO    HandlerThread:31357 [interfaces.py:finish():202] Joined network monitor
2024-08-07 18:37:02,822 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,822 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-07 18:37:02,822 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 3
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send():382] send: stats
2024-08-07 18:37:02,823 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,823 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 4
2024-08-07 18:37:02,823 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,823 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 5
2024-08-07 18:37:02,823 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,823 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send():382] send: summary
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 6
2024-08-07 18:37:02,823 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,823 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-07 18:37:02,823 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,823 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-07 18:37:02,825 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: status_report
2024-08-07 18:37:02,925 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8
2024-08-07 18:37:02,925 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '289657', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:02,925 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96BF2BC0A7B7F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:02,944 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 7
2024-08-07 18:37:02,945 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:02,945 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-07 18:37:02,945 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:02,945 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-07 18:37:03,533 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/config.yaml
2024-08-07 18:37:03,534 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/wandb-summary.json
2024-08-07 18:37:03,534 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/output.log
2024-08-07 18:37:03,726 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d
2024-08-07 18:37:03,726 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5219', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:03,726 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96BF2F78F5BB1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:03,802 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 18:37:03,876 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86
2024-08-07 18:37:03,876 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:03,876 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96BF30084F6BF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:03,876 INFO    wandb-upload_1:31357 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:37:04,098 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8
2024-08-07 18:37:04,098 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '289657', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:04,098 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96BF30BB808FC</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:04,692 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 8
2024-08-07 18:37:04,692 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: poll_exit
2024-08-07 18:37:04,692 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:04,692 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-07 18:37:04,692 DEBUG   SenderThread:31357 [sender.py:send_request():409] send_request: defer
2024-08-07 18:37:04,692 INFO    SenderThread:31357 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-07 18:37:04,692 INFO    SenderThread:31357 [job_builder.py:build():298] Attempting to build job artifact
2024-08-07 18:37:04,692 INFO    SenderThread:31357 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-07 18:37:04,707 INFO    SenderThread:31357 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-07 18:37:04,718 INFO    SenderThread:31357 [sender.py:transition_state():617] send defer: 9
2024-08-07 18:37:04,718 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:37:04,718 INFO    HandlerThread:31357 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-07 18:37:04,718 DEBUG   SenderThread:31357 [sender.py:send():382] send: artifact
2024-08-07 18:37:04,802 DEBUG   HandlerThread:31357 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 18:37:05,348 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd
2024-08-07 18:37:05,348 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:05,348 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96BF355A237EB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:05,363 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769
2024-08-07 18:37:05,363 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:05,363 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96BF35933CC85</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:05,535 INFO    Thread-12 :31357 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_183700-pm4133ad/files/output.log
2024-08-07 18:37:05,875 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c95de776bd9431143042c2eb0dcdd6cad620e62e5e06d22a3e9216ffa69a759d
2024-08-07 18:37:05,875 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5219', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:05,875 ERROR   wandb-upload_0:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96BF377B502CB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:06,081 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7d0aa77307b3078040cdf567389a90ea91d97ac1c3cca6c30950b3d1d65e6d86
2024-08-07 18:37:06,081 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:06,081 ERROR   wandb-upload_1:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96BF383FF775A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:06,397 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/pm4133ad/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103702Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=11ff4770718853d0f58c39e5e8bbe831cd16137be3f62d79d56c86210d8388c8
2024-08-07 18:37:06,397 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '289657', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:06,397 ERROR   wandb-upload_2:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/pm4133ad/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/pm4133ad/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96BF395101E39</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:06,439 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd
2024-08-07 18:37:06,440 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:06,440 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96BF39869C2B4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:06,701 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769
2024-08-07 18:37:06,701 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:06,701 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96BF3A34C5942</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:08,826 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769
2024-08-07 18:37:08,826 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:08,826 ERROR   wandb-upload_3:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96BF4274228D0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:08,826 INFO    wandb-upload_3:31357 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=c98223e23dd66675bd864db965170946f92e757b971a12e91adc0fdfbf6b7769

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:37:08,974 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd
2024-08-07 18:37:08,974 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:37:08,974 ERROR   wandb-upload_4:31357 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96BF42F875681</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:37:08,974 INFO    wandb-upload_4:31357 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/514/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T103705Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=82a115e25a2d266f441bcec00e97ac588bfbddbd74d5cb80477ec33f5effe2dd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
