2024-08-06 19:57:10,286 INFO    StreamThr :2145680 [internal.py:wandb_internal():86] W&B internal server running at pid: 2145680, started at: 2024-08-06 19:57:10.285752
2024-08-06 19:57:10,286 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: status
2024-08-06 19:57:10,288 INFO    WriterThread:2145680 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/run-lchnld2y.wandb
2024-08-06 19:57:10,288 DEBUG   SenderThread:2145680 [sender.py:send():382] send: header
2024-08-06 19:57:10,288 DEBUG   SenderThread:2145680 [sender.py:send():382] send: run
2024-08-06 19:57:10,993 INFO    SenderThread:2145680 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files
2024-08-06 19:57:10,994 INFO    SenderThread:2145680 [sender.py:_start_run_threads():1136] run started: lchnld2y with start time 1722945430.285778
2024-08-06 19:57:11,002 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 19:57:11,002 DEBUG   SenderThread:2145680 [sender.py:send_request():409] send_request: check_version
2024-08-06 19:57:11,105 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 19:57:11,119 DEBUG   HandlerThread:2145680 [system_info.py:__init__():32] System info init
2024-08-06 19:57:11,119 DEBUG   HandlerThread:2145680 [system_info.py:__init__():47] System info init done
2024-08-06 19:57:11,119 INFO    HandlerThread:2145680 [system_monitor.py:start():194] Starting system monitor
2024-08-06 19:57:11,119 INFO    SystemMonitor:2145680 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 19:57:11,120 INFO    HandlerThread:2145680 [system_monitor.py:probe():214] Collecting system info
2024-08-06 19:57:11,120 INFO    SystemMonitor:2145680 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 19:57:11,121 INFO    SystemMonitor:2145680 [interfaces.py:start():190] Started disk monitoring
2024-08-06 19:57:11,123 INFO    SystemMonitor:2145680 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 19:57:11,123 INFO    SystemMonitor:2145680 [interfaces.py:start():190] Started memory monitoring
2024-08-06 19:57:11,124 INFO    SystemMonitor:2145680 [interfaces.py:start():190] Started network monitoring
2024-08-06 19:57:11,132 DEBUG   HandlerThread:2145680 [system_info.py:probe():196] Probing system
2024-08-06 19:57:11,133 DEBUG   HandlerThread:2145680 [system_info.py:_probe_git():181] Probing git
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_info.py:_probe_git():189] Probing git done
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_info.py:probe():244] Probing system done
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T11:57:11.132723', 'startedAt': '2024-08-06T11:57:10.283905', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/qwen2-1.5b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/qwen2-1.5b', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1299.1348928571429, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2217.331, 'min': 800.0, 'max': 5500.0}, {'current': 2225.868, 'min': 800.0, 'max': 5500.0}, {'current': 2225.454, 'min': 800.0, 'max': 5500.0}, {'current': 2259.605, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1916.0, 'min': 800.0, 'max': 5500.0}, {'current': 1207.571, 'min': 800.0, 'max': 5500.0}, {'current': 2088.214, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 2122.921, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2216.743, 'min': 800.0, 'max': 5500.0}, {'current': 2056.619, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1443.242, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.37437438964844}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 19:57:11,135 INFO    HandlerThread:2145680 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 19:57:11,135 INFO    HandlerThread:2145680 [system_monitor.py:probe():227] Publishing system info
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 19:57:11,135 DEBUG   HandlerThread:2145680 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 19:57:11,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/requirements.txt
2024-08-06 19:57:11,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/conda-environment.yaml
2024-08-06 19:57:12,818 DEBUG   HandlerThread:2145680 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 19:57:12,818 INFO    HandlerThread:2145680 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 19:57:12,819 DEBUG   SenderThread:2145680 [sender.py:send():382] send: files
2024-08-06 19:57:12,819 INFO    SenderThread:2145680 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 19:57:12,822 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 19:57:12,822 DEBUG   SenderThread:2145680 [sender.py:send_request():409] send_request: stop_status
2024-08-06 19:57:12,823 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 19:57:12,993 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/conda-environment.yaml
2024-08-06 19:57:12,993 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/wandb-metadata.json
2024-08-06 19:57:13,011 DEBUG   SenderThread:2145680 [sender.py:send():382] send: telemetry
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: config
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: telemetry
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:13,012 WARNING SenderThread:2145680 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: telemetry
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: telemetry
2024-08-06 19:57:13,012 DEBUG   SenderThread:2145680 [sender.py:send():382] send: config
2024-08-06 19:57:13,540 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567
2024-08-06 19:57:13,540 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5176', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:57:13,540 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lchnld2y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921BE440B1EE7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:57:13,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/output.log
2024-08-06 19:57:14,684 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send():382] send: metric
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send():382] send: history
2024-08-06 19:57:14,685 DEBUG   SenderThread:2145680 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:57:14,686 INFO    SenderThread:2145680 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:57:14,740 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567
2024-08-06 19:57:14,740 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5176', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:57:14,740 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lchnld2y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921BE8B93980D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:57:14,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/wandb-summary.json
2024-08-06 19:57:15,686 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 19:57:15,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/output.log
2024-08-06 19:57:16,250 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:57:16,251 DEBUG   SenderThread:2145680 [sender.py:send():382] send: history
2024-08-06 19:57:16,251 DEBUG   SenderThread:2145680 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:57:16,251 INFO    SenderThread:2145680 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:57:16,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/output.log
2024-08-06 19:57:16,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/wandb-summary.json
2024-08-06 19:57:17,007 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567
2024-08-06 19:57:17,007 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5176', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 19:57:17,007 ERROR   wandb-upload_0:2145680 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/lchnld2y/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E921BF1267C2DF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 19:57:17,007 INFO    wandb-upload_0:2145680 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/lchnld2y/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T115713Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=16cf58c3944767c8cf9fa78c313cc53aa398af52a35895b2bad9659b280d7567

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 19:57:17,689 DEBUG   HandlerThread:2145680 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 19:57:17,690 DEBUG   SenderThread:2145680 [sender.py:send():382] send: history
2024-08-06 19:57:17,690 DEBUG   SenderThread:2145680 [sender.py:send_request():409] send_request: summary_record
2024-08-06 19:57:17,690 INFO    SenderThread:2145680 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 19:57:17,994 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/output.log
2024-08-06 19:57:17,995 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/wandb-summary.json
2024-08-06 19:57:18,995 INFO    Thread-12 :2145680 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_195710-lchnld2y/files/output.log
