2024-08-07 11:30:23,975 INFO    StreamThr :2368902 [internal.py:wandb_internal():86] W&B internal server running at pid: 2368902, started at: 2024-08-07 11:30:23.975362
2024-08-07 11:30:23,976 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: status
2024-08-07 11:30:23,977 INFO    WriterThread:2368902 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/run-4n5z4dze.wandb
2024-08-07 11:30:23,977 DEBUG   SenderThread:2368902 [sender.py:send():382] send: header
2024-08-07 11:30:23,977 DEBUG   SenderThread:2368902 [sender.py:send():382] send: run
2024-08-07 11:30:24,126 INFO    SenderThread:2368902 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files
2024-08-07 11:30:24,126 INFO    SenderThread:2368902 [sender.py:_start_run_threads():1136] run started: 4n5z4dze with start time 1723001423.975282
2024-08-07 11:30:24,139 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: check_version
2024-08-07 11:30:24,139 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: check_version
2024-08-07 11:30:24,239 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: run_start
2024-08-07 11:30:24,251 DEBUG   HandlerThread:2368902 [system_info.py:__init__():32] System info init
2024-08-07 11:30:24,251 DEBUG   HandlerThread:2368902 [system_info.py:__init__():47] System info init done
2024-08-07 11:30:24,251 INFO    HandlerThread:2368902 [system_monitor.py:start():194] Starting system monitor
2024-08-07 11:30:24,251 INFO    SystemMonitor:2368902 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-07 11:30:24,252 INFO    HandlerThread:2368902 [system_monitor.py:probe():214] Collecting system info
2024-08-07 11:30:24,252 INFO    SystemMonitor:2368902 [interfaces.py:start():190] Started cpu monitoring
2024-08-07 11:30:24,252 INFO    SystemMonitor:2368902 [interfaces.py:start():190] Started disk monitoring
2024-08-07 11:30:24,253 INFO    SystemMonitor:2368902 [interfaces.py:start():190] Started gpu monitoring
2024-08-07 11:30:24,253 INFO    SystemMonitor:2368902 [interfaces.py:start():190] Started memory monitoring
2024-08-07 11:30:24,253 INFO    SystemMonitor:2368902 [interfaces.py:start():190] Started network monitoring
2024-08-07 11:30:24,261 DEBUG   HandlerThread:2368902 [system_info.py:probe():196] Probing system
2024-08-07 11:30:24,262 DEBUG   HandlerThread:2368902 [system_info.py:_probe_git():181] Probing git
2024-08-07 11:30:24,264 DEBUG   HandlerThread:2368902 [system_info.py:_probe_git():189] Probing git done
2024-08-07 11:30:24,264 DEBUG   HandlerThread:2368902 [system_info.py:probe():244] Probing system done
2024-08-07 11:30:24,264 DEBUG   HandlerThread:2368902 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-07T03:30:24.261366', 'startedAt': '2024-08-07T03:30:23.970083', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1803.7726428571427, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 3433.551, 'min': 800.0, 'max': 5500.0}, {'current': 4735.104, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1899.933, 'min': 800.0, 'max': 5500.0}, {'current': 2256.658, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2322.133, 'min': 800.0, 'max': 5500.0}, {'current': 1100.942, 'min': 800.0, 'max': 5500.0}, {'current': 2169.913, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 4699.267, 'min': 800.0, 'max': 5600.0}, {'current': 3233.303, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2546.146, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1195.955, 'min': 800.0, 'max': 4300.0}, {'current': 1211.084, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1100.112, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 462.0257034301758}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-07 11:30:24,264 INFO    HandlerThread:2368902 [system_monitor.py:probe():224] Finished collecting system info
2024-08-07 11:30:24,264 INFO    HandlerThread:2368902 [system_monitor.py:probe():227] Publishing system info
2024-08-07 11:30:24,264 DEBUG   HandlerThread:2368902 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-07 11:30:24,264 DEBUG   HandlerThread:2368902 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-07 11:30:24,265 DEBUG   HandlerThread:2368902 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-07 11:30:25,127 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/requirements.txt
2024-08-07 11:30:25,127 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/conda-environment.yaml
2024-08-07 11:30:25,963 DEBUG   HandlerThread:2368902 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-07 11:30:25,963 DEBUG   HandlerThread:2368902 [system_info.py:_save_code():90] Saving code
2024-08-07 11:30:25,964 DEBUG   HandlerThread:2368902 [system_info.py:_save_code():111] Saving code done
2024-08-07 11:30:25,964 DEBUG   HandlerThread:2368902 [system_info.py:_save_patches():128] Saving git patches
2024-08-07 11:30:25,967 ERROR   HandlerThread:2368902 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-07 11:30:25,967 DEBUG   HandlerThread:2368902 [system_info.py:_save_patches():170] Saving git patches done
2024-08-07 11:30:25,967 INFO    HandlerThread:2368902 [system_monitor.py:probe():229] Finished publishing system info
2024-08-07 11:30:25,968 DEBUG   SenderThread:2368902 [sender.py:send():382] send: files
2024-08-07 11:30:25,968 INFO    SenderThread:2368902 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-07 11:30:25,968 INFO    SenderThread:2368902 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-07 11:30:25,970 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: stop_status
2024-08-07 11:30:25,970 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-07 11:30:25,970 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: stop_status
2024-08-07 11:30:26,126 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/conda-environment.yaml
2024-08-07 11:30:26,126 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/wandb-metadata.json
2024-08-07 11:30:26,126 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/code/llama/gmm.py
2024-08-07 11:30:26,127 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/code/llama
2024-08-07 11:30:26,127 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/code
2024-08-07 11:30:26,178 DEBUG   SenderThread:2368902 [sender.py:send():382] send: telemetry
2024-08-07 11:30:26,178 DEBUG   SenderThread:2368902 [sender.py:send():382] send: config
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: metric
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: telemetry
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: metric
2024-08-07 11:30:26,179 WARNING SenderThread:2368902 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: telemetry
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: telemetry
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: config
2024-08-07 11:30:26,179 DEBUG   SenderThread:2368902 [sender.py:send():382] send: exit
2024-08-07 11:30:26,179 INFO    SenderThread:2368902 [sender.py:send_exit():589] handling exit code: 1
2024-08-07 11:30:26,179 INFO    SenderThread:2368902 [sender.py:send_exit():591] handling runtime: 1
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:send_exit():597] send defer
2024-08-07 11:30:26,180 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,180 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-07 11:30:26,180 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 1
2024-08-07 11:30:26,180 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,180 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-07 11:30:26,180 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-07 11:30:26,180 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 2
2024-08-07 11:30:26,180 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,180 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-07 11:30:26,180 INFO    HandlerThread:2368902 [system_monitor.py:finish():203] Stopping system monitor
2024-08-07 11:30:26,181 DEBUG   SystemMonitor:2368902 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-07 11:30:26,181 DEBUG   SystemMonitor:2368902 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-07 11:30:26,181 DEBUG   SystemMonitor:2368902 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-07 11:30:26,181 INFO    HandlerThread:2368902 [interfaces.py:finish():202] Joined cpu monitor
2024-08-07 11:30:26,181 INFO    HandlerThread:2368902 [interfaces.py:finish():202] Joined disk monitor
2024-08-07 11:30:26,200 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6
2024-08-07 11:30:26,201 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:26,201 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E954AB12E085D6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:26,230 INFO    HandlerThread:2368902 [interfaces.py:finish():202] Joined gpu monitor
2024-08-07 11:30:26,230 INFO    HandlerThread:2368902 [interfaces.py:finish():202] Joined memory monitor
2024-08-07 11:30:26,230 INFO    HandlerThread:2368902 [interfaces.py:finish():202] Joined network monitor
2024-08-07 11:30:26,231 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 3
2024-08-07 11:30:26,231 DEBUG   SenderThread:2368902 [sender.py:send():382] send: stats
2024-08-07 11:30:26,231 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,231 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-07 11:30:26,231 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 4
2024-08-07 11:30:26,231 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,231 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-07 11:30:26,231 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 5
2024-08-07 11:30:26,231 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,231 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-07 11:30:26,231 DEBUG   SenderThread:2368902 [sender.py:send():382] send: summary
2024-08-07 11:30:26,231 INFO    SenderThread:2368902 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 11:30:26,232 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,232 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-07 11:30:26,232 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 6
2024-08-07 11:30:26,232 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,232 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-07 11:30:26,232 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,232 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-07 11:30:26,233 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: status_report
2024-08-07 11:30:26,271 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68
2024-08-07 11:30:26,271 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:26,271 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E954AB13C94CD0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:26,325 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 7
2024-08-07 11:30:26,325 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:26,325 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-07 11:30:26,325 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:26,325 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-07 11:30:27,127 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/config.yaml
2024-08-07 11:30:27,128 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/wandb-summary.json
2024-08-07 11:30:27,128 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/output.log
2024-08-07 11:30:27,178 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 11:30:27,334 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6
2024-08-07 11:30:27,335 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:27,335 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E954AB56227B37</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:27,444 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68
2024-08-07 11:30:27,444 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:27,444 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E954AB5C0B4819</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:27,444 INFO    wandb-upload_1:2368902 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 11:30:28,192 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 8
2024-08-07 11:30:28,192 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: poll_exit
2024-08-07 11:30:28,193 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:28,193 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-07 11:30:28,193 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:28,193 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-07 11:30:28,193 INFO    SenderThread:2368902 [job_builder.py:build():298] Attempting to build job artifact
2024-08-07 11:30:28,194 INFO    SenderThread:2368902 [job_builder.py:_get_source_type():439] no source found
2024-08-07 11:30:28,194 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 9
2024-08-07 11:30:28,194 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:28,194 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-07 11:30:28,194 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:28,194 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 9
2024-08-07 11:30:28,194 INFO    SenderThread:2368902 [dir_watcher.py:finish():358] shutting down directory watcher
2024-08-07 11:30:29,128 INFO    Thread-12 :2368902 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/output.log
2024-08-07 11:30:29,129 INFO    SenderThread:2368902 [dir_watcher.py:finish():388] scan: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files
2024-08-07 11:30:29,130 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/wandb-summary.json wandb-summary.json
2024-08-07 11:30:29,130 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/requirements.txt requirements.txt
2024-08-07 11:30:29,130 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/output.log output.log
2024-08-07 11:30:29,134 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/config.yaml config.yaml
2024-08-07 11:30:29,134 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/wandb-metadata.json wandb-metadata.json
2024-08-07 11:30:29,135 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/conda-environment.yaml conda-environment.yaml
2024-08-07 11:30:29,144 INFO    SenderThread:2368902 [dir_watcher.py:finish():402] scan save: /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/code/llama/gmm.py code/llama/gmm.py
2024-08-07 11:30:29,144 INFO    SenderThread:2368902 [sender.py:transition_state():617] send defer: 10
2024-08-07 11:30:29,144 DEBUG   HandlerThread:2368902 [handler.py:handle_request():146] handle_request: defer
2024-08-07 11:30:29,145 INFO    HandlerThread:2368902 [handler.py:handle_request_defer():172] handle defer: 10
2024-08-07 11:30:29,145 DEBUG   SenderThread:2368902 [sender.py:send_request():409] send_request: defer
2024-08-07 11:30:29,145 INFO    SenderThread:2368902 [sender.py:send_request_defer():613] handle sender defer: 10
2024-08-07 11:30:29,145 INFO    SenderThread:2368902 [file_pusher.py:finish():175] shutting down file pusher
2024-08-07 11:30:29,267 INFO    wandb-upload_2:2368902 [upload_job.py:push():131] Uploaded file /home/rwkv/JL/GMM/llama/wandb/run-20240807_113023-4n5z4dze/files/wandb-summary.json
2024-08-07 11:30:29,274 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b32bbac70d192e89d0e275dcab5997c7d957aaf2928779dd18974549ac4de43c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b32bbac70d192e89d0e275dcab5997c7d957aaf2928779dd18974549ac4de43c
2024-08-07 11:30:29,274 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,274 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/output.log</Resource><Region>wandb-local</Region><RequestId>17E954ABC9BB5B0E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,289 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=81383eb3228be7398a77618c74cf0c826768d498c57e2bc6e84db79ad5d9c151: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=81383eb3228be7398a77618c74cf0c826768d498c57e2bc6e84db79ad5d9c151
2024-08-07 11:30:29,289 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,289 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E954ABCAEF7DF0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,360 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1bd34d05010206cdad637e5d119578871bdfbe93a46a737fbdfb7b7e3f406b1b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1bd34d05010206cdad637e5d119578871bdfbe93a46a737fbdfb7b7e3f406b1b
2024-08-07 11:30:29,360 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,360 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E954ABCF2C210B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,372 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12b26b4d32ad8172e0e5654af47dc7369133c51231bb36e6cd588beadba13e59: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12b26b4d32ad8172e0e5654af47dc7369133c51231bb36e6cd588beadba13e59
2024-08-07 11:30:29,372 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11185', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,372 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E954ABCFDF7681</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,567 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b207c8033141458fc28af6383125ad224f244afa471341d11eeb374570dc14d6
2024-08-07 11:30:29,567 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,567 ERROR   wandb-upload_0:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E954ABDB3FC8D5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,768 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68
2024-08-07 11:30:29,768 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:29,768 ERROR   wandb-upload_1:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E954ABE679F48F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:29,768 INFO    wandb-upload_1:2368902 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033026Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b0ec7fb2ab874bfb0ab03717e6245bfb06c73da988e1850f819d67f91a68ac68

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 11:30:30,369 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=81383eb3228be7398a77618c74cf0c826768d498c57e2bc6e84db79ad5d9c151: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/requirements.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=81383eb3228be7398a77618c74cf0c826768d498c57e2bc6e84db79ad5d9c151
2024-08-07 11:30:30,369 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:30,369 ERROR   wandb-upload_3:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/requirements.txt</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/requirements.txt</Resource><Region>wandb-local</Region><RequestId>17E954AC0B125714</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:30,473 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b32bbac70d192e89d0e275dcab5997c7d957aaf2928779dd18974549ac4de43c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/output.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=b32bbac70d192e89d0e275dcab5997c7d957aaf2928779dd18974549ac4de43c
2024-08-07 11:30:30,473 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8253', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:30,473 ERROR   wandb-upload_4:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/output.log</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/output.log</Resource><Region>wandb-local</Region><RequestId>17E954AC110C1D34</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:30,480 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12b26b4d32ad8172e0e5654af47dc7369133c51231bb36e6cd588beadba13e59: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/config.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=12b26b4d32ad8172e0e5654af47dc7369133c51231bb36e6cd588beadba13e59
2024-08-07 11:30:30,480 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11185', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:30,480 ERROR   wandb-upload_5:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/config.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/config.yaml</Resource><Region>wandb-local</Region><RequestId>17E954AC112DCA6E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 11:30:30,523 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1bd34d05010206cdad637e5d119578871bdfbe93a46a737fbdfb7b7e3f406b1b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T033029Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1bd34d05010206cdad637e5d119578871bdfbe93a46a737fbdfb7b7e3f406b1b
2024-08-07 11:30:30,523 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '8681', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 11:30:30,523 ERROR   wandb-upload_6:2368902 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/4n5z4dze/conda-environment.yaml</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/4n5z4dze/conda-environment.yaml</Resource><Region>wandb-local</Region><RequestId>17E954AC142B0549</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
