2024-08-08 17:43:31,230 INFO    StreamThr :304574 [internal.py:wandb_internal():86] W&B internal server running at pid: 304574, started at: 2024-08-08 17:43:31.229804
2024-08-08 17:43:31,231 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: status
2024-08-08 17:43:31,231 INFO    WriterThread:304574 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/run-gein88r4.wandb
2024-08-08 17:43:31,232 DEBUG   SenderThread:304574 [sender.py:send():382] send: header
2024-08-08 17:43:31,266 DEBUG   SenderThread:304574 [sender.py:send():382] send: run
2024-08-08 17:43:31,507 INFO    SenderThread:304574 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files
2024-08-08 17:43:31,507 INFO    SenderThread:304574 [sender.py:_start_run_threads():1136] run started: gein88r4 with start time 1723110211.229815
2024-08-08 17:43:31,513 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 17:43:31,513 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: check_version
2024-08-08 17:43:31,611 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 17:43:31,619 DEBUG   HandlerThread:304574 [system_info.py:__init__():32] System info init
2024-08-08 17:43:31,619 DEBUG   HandlerThread:304574 [system_info.py:__init__():47] System info init done
2024-08-08 17:43:31,619 INFO    HandlerThread:304574 [system_monitor.py:start():194] Starting system monitor
2024-08-08 17:43:31,620 INFO    SystemMonitor:304574 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 17:43:31,620 INFO    HandlerThread:304574 [system_monitor.py:probe():214] Collecting system info
2024-08-08 17:43:31,620 INFO    SystemMonitor:304574 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 17:43:31,620 INFO    SystemMonitor:304574 [interfaces.py:start():190] Started disk monitoring
2024-08-08 17:43:31,621 INFO    SystemMonitor:304574 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 17:43:31,621 INFO    SystemMonitor:304574 [interfaces.py:start():190] Started memory monitoring
2024-08-08 17:43:31,621 INFO    SystemMonitor:304574 [interfaces.py:start():190] Started network monitoring
2024-08-08 17:43:31,628 DEBUG   HandlerThread:304574 [system_info.py:probe():196] Probing system
2024-08-08 17:43:31,630 DEBUG   HandlerThread:304574 [system_info.py:_probe_git():181] Probing git
2024-08-08 17:43:31,638 DEBUG   HandlerThread:304574 [system_info.py:_probe_git():189] Probing git done
2024-08-08 17:43:31,638 DEBUG   HandlerThread:304574 [system_info.py:probe():244] Probing system done
2024-08-08 17:43:31,638 DEBUG   HandlerThread:304574 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T09:43:31.628431', 'startedAt': '2024-08-08T09:43:31.224971', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/Gemma-2B', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1434.955642857143, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 5470.96, 'min': 800.0, 'max': 5500.0}, {'current': 1284.429, 'min': 800.0, 'max': 5500.0}, {'current': 5409.858, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5237.108, 'min': 800.0, 'max': 5500.0}, {'current': 1180.895, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5036.065, 'min': 800.0, 'max': 5600.0}, {'current': 4343.631, 'min': 800.0, 'max': 5600.0}, {'current': 5474.707, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 3456.711, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5481.888, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1100.359, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.0288848876953}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 17:43:31,639 INFO    HandlerThread:304574 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 17:43:31,639 INFO    HandlerThread:304574 [system_monitor.py:probe():227] Publishing system info
2024-08-08 17:43:31,639 DEBUG   HandlerThread:304574 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 17:43:31,639 DEBUG   HandlerThread:304574 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 17:43:31,639 DEBUG   HandlerThread:304574 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 17:43:32,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/conda-environment.yaml
2024-08-08 17:43:32,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/requirements.txt
2024-08-08 17:43:33,313 DEBUG   HandlerThread:304574 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 17:43:33,313 DEBUG   HandlerThread:304574 [system_info.py:_save_code():90] Saving code
2024-08-08 17:43:33,314 DEBUG   HandlerThread:304574 [system_info.py:_save_code():111] Saving code done
2024-08-08 17:43:33,314 DEBUG   HandlerThread:304574 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 17:43:33,354 DEBUG   HandlerThread:304574 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 17:43:33,355 INFO    HandlerThread:304574 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 17:43:33,359 DEBUG   SenderThread:304574 [sender.py:send():382] send: files
2024-08-08 17:43:33,359 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 17:43:33,360 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 17:43:33,360 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 17:43:33,368 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 17:43:33,368 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: stop_status
2024-08-08 17:43:33,370 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/conda-environment.yaml
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-metadata.json
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/diff.patch
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/code/llama/gmm.py
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/code/llama
2024-08-08 17:43:33,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/code
2024-08-08 17:43:33,557 DEBUG   SenderThread:304574 [sender.py:send():382] send: telemetry
2024-08-08 17:43:33,557 DEBUG   SenderThread:304574 [sender.py:send():382] send: config
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: telemetry
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:33,558 WARNING SenderThread:304574 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: telemetry
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: telemetry
2024-08-08 17:43:33,558 DEBUG   SenderThread:304574 [sender.py:send():382] send: config
2024-08-08 17:43:33,656 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e
2024-08-08 17:43:33,656 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:33,656 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B79C20368556</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:33,715 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17
2024-08-08 17:43:33,715 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:33,715 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B79C1F8B6B93</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:33,854 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5
2024-08-08 17:43:33,854 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291741', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:33,854 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B79C20C4B584</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:34,507 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:34,785 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17
2024-08-08 17:43:34,785 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:34,785 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B79C6378C57F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:34,785 INFO    wandb-upload_1:304574 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:43:34,853 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e
2024-08-08 17:43:34,853 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:34,853 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B79C670ED885</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:34,853 INFO    wandb-upload_0:304574 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 17:43:35,304 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5
2024-08-08 17:43:35,304 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291741', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:35,304 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B79C6F7D608F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:36,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:36,560 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 17:43:37,017 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send():382] send: metric
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send():382] send: history
2024-08-08 17:43:37,019 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: summary_record
2024-08-08 17:43:37,019 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:43:37,287 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17
2024-08-08 17:43:37,287 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:37,287 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B79CF86EE19C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:37,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-summary.json
2024-08-08 17:43:37,511 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e
2024-08-08 17:43:37,511 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:37,511 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B79D00460A22</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:37,872 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5
2024-08-08 17:43:37,872 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291741', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:37,872 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B79D11F97CB4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:38,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:39,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:40,275 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 17:43:40,276 DEBUG   SenderThread:304574 [sender.py:send():382] send: history
2024-08-08 17:43:40,276 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: summary_record
2024-08-08 17:43:40,277 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:43:40,508 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-summary.json
2024-08-08 17:43:41,509 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:42,198 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e
2024-08-08 17:43:42,198 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:42,198 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B79E1D2E84D6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:42,277 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 17:43:42,362 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17
2024-08-08 17:43:42,362 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:42,362 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B79E26F7258A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:42,509 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:42,758 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5
2024-08-08 17:43:42,758 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291741', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:42,758 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B79E3602B08D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:43,550 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 17:43:43,551 DEBUG   SenderThread:304574 [sender.py:send():382] send: history
2024-08-08 17:43:43,551 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: summary_record
2024-08-08 17:43:43,551 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:43:44,509 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-summary.json
2024-08-08 17:43:45,509 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:46,510 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:46,931 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 17:43:46,931 DEBUG   SenderThread:304574 [sender.py:send():382] send: history
2024-08-08 17:43:46,931 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: summary_record
2024-08-08 17:43:46,932 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:43:47,510 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-summary.json
2024-08-08 17:43:47,932 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 17:43:48,366 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 17:43:48,367 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: stop_status
2024-08-08 17:43:48,368 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 17:43:48,510 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:49,510 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:50,308 DEBUG   HandlerThread:304574 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 17:43:50,309 DEBUG   SenderThread:304574 [sender.py:send():382] send: history
2024-08-08 17:43:50,309 DEBUG   SenderThread:304574 [sender.py:send_request():409] send_request: summary_record
2024-08-08 17:43:50,309 INFO    SenderThread:304574 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 17:43:50,510 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/wandb-summary.json
2024-08-08 17:43:50,628 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=c46416e15fe2f0c0ad590f334acbb1fa34d4df61eb0c57abe87c01be788f4b7e
2024-08-08 17:43:50,628 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5249', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:50,628 ERROR   wandb-upload_0:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9B7A013ABF3FB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:51,017 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=785a81619f9e725b4558b03dc120810ee4a2c8f7d577364649c6eb85370d2a17
2024-08-08 17:43:51,017 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:51,017 ERROR   wandb-upload_1:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9B7A02AD5D756</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:51,511 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
2024-08-08 17:43:52,077 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/gein88r4/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T094333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=19ea169a61e1ef0d8ddf34a6ad9df2525306c7b79d47f135b7d4709db7170ad5
2024-08-08 17:43:52,077 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291741', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 17:43:52,077 ERROR   wandb-upload_2:304574 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/gein88r4/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/gein88r4/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9B7A0699B74F5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 17:43:52,511 INFO    Thread-12 :304574 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_174331-gein88r4/files/output.log
