2024-08-07 18:14:46,968 INFO    StreamThr :21514 [internal.py:wandb_internal():86] W&B internal server running at pid: 21514, started at: 2024-08-07 18:14:46.967852
2024-08-07 18:14:46,968 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: status
2024-08-07 18:14:46,969 INFO    WriterThread:21514 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/run-n3at9lbt.wandb
2024-08-07 18:14:46,969 DEBUG   SenderThread:21514 [sender.py:send():382] send: header
2024-08-07 18:14:46,998 DEBUG   SenderThread:21514 [sender.py:send():382] send: run
2024-08-07 18:14:47,147 INFO    SenderThread:21514 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files
2024-08-07 18:14:47,148 INFO    SenderThread:21514 [sender.py:_start_run_threads():1136] run started: n3at9lbt with start time 1723025686.967894
2024-08-07 18:14:47,161 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: check_version
2024-08-07 18:14:47,161 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: check_version
2024-08-07 18:14:47,267 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: run_start
2024-08-07 18:14:47,275 DEBUG   HandlerThread:21514 [system_info.py:__init__():32] System info init
2024-08-07 18:14:47,275 DEBUG   HandlerThread:21514 [system_info.py:__init__():47] System info init done
2024-08-07 18:14:47,275 INFO    HandlerThread:21514 [system_monitor.py:start():194] Starting system monitor
2024-08-07 18:14:47,275 INFO    SystemMonitor:21514 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-07 18:14:47,275 INFO    HandlerThread:21514 [system_monitor.py:probe():214] Collecting system info
2024-08-07 18:14:47,275 INFO    SystemMonitor:21514 [interfaces.py:start():190] Started cpu monitoring
2024-08-07 18:14:47,276 INFO    SystemMonitor:21514 [interfaces.py:start():190] Started disk monitoring
2024-08-07 18:14:47,276 INFO    SystemMonitor:21514 [interfaces.py:start():190] Started gpu monitoring
2024-08-07 18:14:47,276 INFO    SystemMonitor:21514 [interfaces.py:start():190] Started memory monitoring
2024-08-07 18:14:47,277 INFO    SystemMonitor:21514 [interfaces.py:start():190] Started network monitoring
2024-08-07 18:14:47,283 DEBUG   HandlerThread:21514 [system_info.py:probe():196] Probing system
2024-08-07 18:14:47,284 DEBUG   HandlerThread:21514 [system_info.py:_probe_git():181] Probing git
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_info.py:_probe_git():189] Probing git done
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_info.py:probe():244] Probing system done
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-07T10:14:47.283580', 'startedAt': '2024-08-07T10:14:46.963371', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1567.3869642857146, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2563.807, 'min': 800.0, 'max': 5500.0}, {'current': 3586.486, 'min': 800.0, 'max': 5500.0}, {'current': 5478.544, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 4939.067, 'min': 800.0, 'max': 5500.0}, {'current': 5383.796, 'min': 800.0, 'max': 5500.0}, {'current': 5271.645, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 5482.173, 'min': 800.0, 'max': 5600.0}, {'current': 3683.839, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 5296.061, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1246.012, 'min': 800.0, 'max': 4300.0}, {'current': 2727.479, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 474.6696434020996}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-07 18:14:47,288 INFO    HandlerThread:21514 [system_monitor.py:probe():224] Finished collecting system info
2024-08-07 18:14:47,288 INFO    HandlerThread:21514 [system_monitor.py:probe():227] Publishing system info
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-07 18:14:47,288 DEBUG   HandlerThread:21514 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-07 18:14:48,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/requirements.txt
2024-08-07 18:14:48,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/conda-environment.yaml
2024-08-07 18:14:48,986 DEBUG   HandlerThread:21514 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-07 18:14:48,986 DEBUG   HandlerThread:21514 [system_info.py:_save_code():90] Saving code
2024-08-07 18:14:48,987 DEBUG   HandlerThread:21514 [system_info.py:_save_code():111] Saving code done
2024-08-07 18:14:48,987 DEBUG   HandlerThread:21514 [system_info.py:_save_patches():128] Saving git patches
2024-08-07 18:14:49,027 DEBUG   HandlerThread:21514 [system_info.py:_save_patches():170] Saving git patches done
2024-08-07 18:14:49,028 INFO    HandlerThread:21514 [system_monitor.py:probe():229] Finished publishing system info
2024-08-07 18:14:49,031 DEBUG   SenderThread:21514 [sender.py:send():382] send: files
2024-08-07 18:14:49,031 INFO    SenderThread:21514 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-07 18:14:49,032 INFO    SenderThread:21514 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-07 18:14:49,033 INFO    SenderThread:21514 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-07 18:14:49,041 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: stop_status
2024-08-07 18:14:49,041 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: stop_status
2024-08-07 18:14:49,048 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/conda-environment.yaml
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/wandb-metadata.json
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/diff.patch
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/code/llama/gmm.py
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/code/llama
2024-08-07 18:14:49,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/code
2024-08-07 18:14:49,208 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25
2024-08-07 18:14:49,208 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5215', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:49,208 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96ABC3FA4C39B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: telemetry
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: config
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: metric
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: telemetry
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: metric
2024-08-07 18:14:49,229 WARNING SenderThread:21514 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: telemetry
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: telemetry
2024-08-07 18:14:49,229 DEBUG   SenderThread:21514 [sender.py:send():382] send: config
2024-08-07 18:14:49,322 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475
2024-08-07 18:14:49,322 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:49,322 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96ABC45F09C04</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:49,353 DEBUG   SenderThread:21514 [sender.py:send():382] send: exit
2024-08-07 18:14:49,353 INFO    SenderThread:21514 [sender.py:send_exit():589] handling exit code: 1
2024-08-07 18:14:49,353 INFO    SenderThread:21514 [sender.py:send_exit():591] handling runtime: 2
2024-08-07 18:14:49,354 INFO    SenderThread:21514 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:14:49,354 INFO    SenderThread:21514 [sender.py:send_exit():597] send defer
2024-08-07 18:14:49,354 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,354 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-07 18:14:49,354 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,354 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-07 18:14:49,354 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 1
2024-08-07 18:14:49,354 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,354 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-07 18:14:49,355 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,355 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-07 18:14:49,355 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 2
2024-08-07 18:14:49,355 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,355 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-07 18:14:49,355 INFO    HandlerThread:21514 [system_monitor.py:finish():203] Stopping system monitor
2024-08-07 18:14:49,355 DEBUG   SystemMonitor:21514 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-07 18:14:49,355 DEBUG   SystemMonitor:21514 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-07 18:14:49,355 DEBUG   SystemMonitor:21514 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-07 18:14:49,355 INFO    HandlerThread:21514 [interfaces.py:finish():202] Joined cpu monitor
2024-08-07 18:14:49,356 INFO    HandlerThread:21514 [interfaces.py:finish():202] Joined disk monitor
2024-08-07 18:14:49,374 INFO    HandlerThread:21514 [interfaces.py:finish():202] Joined gpu monitor
2024-08-07 18:14:49,375 INFO    HandlerThread:21514 [interfaces.py:finish():202] Joined memory monitor
2024-08-07 18:14:49,375 INFO    HandlerThread:21514 [interfaces.py:finish():202] Joined network monitor
2024-08-07 18:14:49,375 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 3
2024-08-07 18:14:49,375 DEBUG   SenderThread:21514 [sender.py:send():382] send: stats
2024-08-07 18:14:49,375 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,375 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-07 18:14:49,375 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 4
2024-08-07 18:14:49,375 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,375 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-07 18:14:49,375 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-07 18:14:49,375 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 5
2024-08-07 18:14:49,375 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,375 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-07 18:14:49,376 DEBUG   SenderThread:21514 [sender.py:send():382] send: summary
2024-08-07 18:14:49,376 INFO    SenderThread:21514 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 18:14:49,376 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,376 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-07 18:14:49,376 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 6
2024-08-07 18:14:49,376 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,376 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-07 18:14:49,376 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,376 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-07 18:14:49,377 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: status_report
2024-08-07 18:14:49,490 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 7
2024-08-07 18:14:49,490 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:49,490 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-07 18:14:49,490 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:49,490 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-07 18:14:49,693 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb
2024-08-07 18:14:49,693 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '287188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:49,693 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96ABC45D468B2</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:50,148 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/config.yaml
2024-08-07 18:14:50,149 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/wandb-summary.json
2024-08-07 18:14:50,149 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/output.log
2024-08-07 18:14:50,353 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 18:14:50,369 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25
2024-08-07 18:14:50,369 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5215', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:50,369 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96ABC84B5A23F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:50,643 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475
2024-08-07 18:14:50,643 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:50,643 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96ABC94F6FD75</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:50,643 INFO    wandb-upload_1:21514 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:14:51,046 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb
2024-08-07 18:14:51,046 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '287188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:51,046 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96ABCA383276F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:51,255 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 8
2024-08-07 18:14:51,255 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: poll_exit
2024-08-07 18:14:51,256 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:51,256 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-07 18:14:51,256 DEBUG   SenderThread:21514 [sender.py:send_request():409] send_request: defer
2024-08-07 18:14:51,256 INFO    SenderThread:21514 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-07 18:14:51,256 INFO    SenderThread:21514 [job_builder.py:build():298] Attempting to build job artifact
2024-08-07 18:14:51,257 INFO    SenderThread:21514 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-07 18:14:51,272 INFO    SenderThread:21514 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-07 18:14:51,284 INFO    SenderThread:21514 [sender.py:transition_state():617] send defer: 9
2024-08-07 18:14:51,284 DEBUG   SenderThread:21514 [sender.py:send():382] send: artifact
2024-08-07 18:14:51,286 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: defer
2024-08-07 18:14:51,286 INFO    HandlerThread:21514 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-07 18:14:51,354 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 18:14:51,927 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89
2024-08-07 18:14:51,927 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:51,927 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96ABCDE817B48</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:52,149 INFO    Thread-12 :21514 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_181446-n3at9lbt/files/output.log
2024-08-07 18:14:52,779 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25
2024-08-07 18:14:52,779 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5215', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:52,779 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96ABD14616038</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:52,933 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029
2024-08-07 18:14:52,933 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:52,933 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96ABD1D93450C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:53,028 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475
2024-08-07 18:14:53,029 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:53,029 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96ABD2336BD75</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:53,162 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89
2024-08-07 18:14:53,162 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:53,162 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96ABD29D9712F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:53,504 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb
2024-08-07 18:14:53,504 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '287188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:53,504 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96ABD38B0E39A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:54,095 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029
2024-08-07 18:14:54,095 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:54,096 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96ABD62DC5DAF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:55,421 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89
2024-08-07 18:14:55,422 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:55,422 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96ABDB09FA564</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:55,422 INFO    wandb-upload_4:21514 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:14:56,357 DEBUG   HandlerThread:21514 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 18:14:56,485 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029
2024-08-07 18:14:56,485 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:56,485 ERROR   wandb-upload_3:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E96ABDF100E75E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:56,485 INFO    wandb-upload_3:21514 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=00b1ea9f35bca313f4acf26b8f0c408682239345b0015e7e8136b0302d5ee029

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 18:14:57,712 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=bdb1d75638382f208d9202119ef188ff6395e68325d25f56ffa7734d37374f25
2024-08-07 18:14:57,712 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5215', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:57,712 ERROR   wandb-upload_0:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E96ABE3A5B16DD</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:57,842 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=7a806b74ad1d3c6da2419798748794434869c0b1770980cd28234caa49e6b475
2024-08-07 18:14:57,843 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:57,843 ERROR   wandb-upload_1:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E96ABE41994FF0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:14:58,017 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/n3at9lbt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101449Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=744f5883c4da60167ff316324ce0c128c551cb764d2dcb6bd585bca3db024deb
2024-08-07 18:14:58,017 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '287188', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:14:58,017 ERROR   wandb-upload_2:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/n3at9lbt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/n3at9lbt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E96ABE3F63C1DF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 18:15:00,361 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T101451Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=b0bc68de9cb3122006ed55f7406d0a3237dd9da91de7ff2fed1489eb76146d89
2024-08-07 18:15:00,361 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 18:15:00,361 ERROR   wandb-upload_4:21514 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/505/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E96ABED719ACF4</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
