2024-08-07 21:07:33,575 INFO    StreamThr :64391 [internal.py:wandb_internal():86] W&B internal server running at pid: 64391, started at: 2024-08-07 21:07:33.575628
2024-08-07 21:07:33,576 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: status
2024-08-07 21:07:33,577 INFO    WriterThread:64391 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/run-uojuhshy.wandb
2024-08-07 21:07:33,577 DEBUG   SenderThread:64391 [sender.py:send():382] send: header
2024-08-07 21:07:33,610 DEBUG   SenderThread:64391 [sender.py:send():382] send: run
2024-08-07 21:07:35,248 INFO    SenderThread:64391 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files
2024-08-07 21:07:35,248 INFO    SenderThread:64391 [sender.py:_start_run_threads():1136] run started: uojuhshy with start time 1723036053.575682
2024-08-07 21:07:35,254 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: check_version
2024-08-07 21:07:35,254 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: check_version
2024-08-07 21:07:35,374 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: run_start
2024-08-07 21:07:35,383 DEBUG   HandlerThread:64391 [system_info.py:__init__():32] System info init
2024-08-07 21:07:35,383 DEBUG   HandlerThread:64391 [system_info.py:__init__():47] System info init done
2024-08-07 21:07:35,383 INFO    HandlerThread:64391 [system_monitor.py:start():194] Starting system monitor
2024-08-07 21:07:35,384 INFO    SystemMonitor:64391 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-07 21:07:35,384 INFO    HandlerThread:64391 [system_monitor.py:probe():214] Collecting system info
2024-08-07 21:07:35,384 INFO    SystemMonitor:64391 [interfaces.py:start():190] Started cpu monitoring
2024-08-07 21:07:35,384 INFO    SystemMonitor:64391 [interfaces.py:start():190] Started disk monitoring
2024-08-07 21:07:35,385 INFO    SystemMonitor:64391 [interfaces.py:start():190] Started gpu monitoring
2024-08-07 21:07:35,385 INFO    SystemMonitor:64391 [interfaces.py:start():190] Started memory monitoring
2024-08-07 21:07:35,386 INFO    SystemMonitor:64391 [interfaces.py:start():190] Started network monitoring
2024-08-07 21:07:35,394 DEBUG   HandlerThread:64391 [system_info.py:probe():196] Probing system
2024-08-07 21:07:35,395 DEBUG   HandlerThread:64391 [system_info.py:_probe_git():181] Probing git
2024-08-07 21:07:35,398 DEBUG   HandlerThread:64391 [system_info.py:_probe_git():189] Probing git done
2024-08-07 21:07:35,398 DEBUG   HandlerThread:64391 [system_info.py:probe():244] Probing system done
2024-08-07 21:07:35,398 DEBUG   HandlerThread:64391 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-07T13:07:35.394239', 'startedAt': '2024-08-07T13:07:33.571161', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--use_lora', 'True', '--init_lora_weights', 'pissa_niter_4', '--target_modules', 'q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj', '--lora_rank', '32', '--lora_alpha', '32', '--lora_dropout', '0', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1643.2776785714284, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1720.535, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1840.824, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1944.023, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1727.664, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1749.292, 'min': 800.0, 'max': 5600.0}, {'current': 1755.394, 'min': 800.0, 'max': 5600.0}, {'current': 1886.126, 'min': 800.0, 'max': 5600.0}, {'current': 1852.97, 'min': 800.0, 'max': 5600.0}, {'current': 2088.045, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1771.782, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 474.68863677978516}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-07 21:07:35,398 INFO    HandlerThread:64391 [system_monitor.py:probe():224] Finished collecting system info
2024-08-07 21:07:35,398 INFO    HandlerThread:64391 [system_monitor.py:probe():227] Publishing system info
2024-08-07 21:07:35,398 DEBUG   HandlerThread:64391 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-07 21:07:35,399 DEBUG   HandlerThread:64391 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-07 21:07:35,399 DEBUG   HandlerThread:64391 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-07 21:07:36,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/conda-environment.yaml
2024-08-07 21:07:36,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/requirements.txt
2024-08-07 21:07:37,144 DEBUG   HandlerThread:64391 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-07 21:07:37,144 DEBUG   HandlerThread:64391 [system_info.py:_save_code():90] Saving code
2024-08-07 21:07:37,145 DEBUG   HandlerThread:64391 [system_info.py:_save_code():111] Saving code done
2024-08-07 21:07:37,145 DEBUG   HandlerThread:64391 [system_info.py:_save_patches():128] Saving git patches
2024-08-07 21:07:37,182 DEBUG   HandlerThread:64391 [system_info.py:_save_patches():170] Saving git patches done
2024-08-07 21:07:37,183 INFO    HandlerThread:64391 [system_monitor.py:probe():229] Finished publishing system info
2024-08-07 21:07:37,184 DEBUG   SenderThread:64391 [sender.py:send():382] send: files
2024-08-07 21:07:37,184 INFO    SenderThread:64391 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-07 21:07:37,184 INFO    SenderThread:64391 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-07 21:07:37,184 INFO    SenderThread:64391 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-07 21:07:37,187 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: stop_status
2024-08-07 21:07:37,187 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-07 21:07:37,187 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: stop_status
2024-08-07 21:07:37,248 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/conda-environment.yaml
2024-08-07 21:07:37,248 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/code/llama/gmm.py
2024-08-07 21:07:37,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/diff.patch
2024-08-07 21:07:37,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/wandb-metadata.json
2024-08-07 21:07:37,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/code
2024-08-07 21:07:37,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/code/llama
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: telemetry
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: config
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: metric
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: telemetry
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: metric
2024-08-07 21:07:37,371 WARNING SenderThread:64391 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: telemetry
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: telemetry
2024-08-07 21:07:37,371 DEBUG   SenderThread:64391 [sender.py:send():382] send: config
2024-08-07 21:07:37,462 DEBUG   SenderThread:64391 [sender.py:send():382] send: exit
2024-08-07 21:07:37,462 INFO    SenderThread:64391 [sender.py:send_exit():589] handling exit code: 1
2024-08-07 21:07:37,462 INFO    SenderThread:64391 [sender.py:send_exit():591] handling runtime: 2
2024-08-07 21:07:37,462 INFO    SenderThread:64391 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 21:07:37,462 INFO    SenderThread:64391 [sender.py:send_exit():597] send defer
2024-08-07 21:07:37,463 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-07 21:07:37,463 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,463 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-07 21:07:37,463 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 1
2024-08-07 21:07:37,463 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-07 21:07:37,463 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,463 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-07 21:07:37,463 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 2
2024-08-07 21:07:37,463 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [system_monitor.py:finish():203] Stopping system monitor
2024-08-07 21:07:37,463 DEBUG   SystemMonitor:64391 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-07 21:07:37,463 DEBUG   SystemMonitor:64391 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-07 21:07:37,463 DEBUG   SystemMonitor:64391 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [interfaces.py:finish():202] Joined cpu monitor
2024-08-07 21:07:37,463 INFO    HandlerThread:64391 [interfaces.py:finish():202] Joined disk monitor
2024-08-07 21:07:37,483 INFO    HandlerThread:64391 [interfaces.py:finish():202] Joined gpu monitor
2024-08-07 21:07:37,483 INFO    HandlerThread:64391 [interfaces.py:finish():202] Joined memory monitor
2024-08-07 21:07:37,483 INFO    HandlerThread:64391 [interfaces.py:finish():202] Joined network monitor
2024-08-07 21:07:37,483 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,483 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-07 21:07:37,483 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 3
2024-08-07 21:07:37,483 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,483 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-07 21:07:37,483 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,483 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-07 21:07:37,483 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 4
2024-08-07 21:07:37,483 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,483 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-07 21:07:37,484 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 5
2024-08-07 21:07:37,484 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,484 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-07 21:07:37,484 DEBUG   SenderThread:64391 [sender.py:send():382] send: summary
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-07 21:07:37,484 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 6
2024-08-07 21:07:37,484 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,484 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-07 21:07:37,484 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,484 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-07 21:07:37,485 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: status_report
2024-08-07 21:07:37,494 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c
2024-08-07 21:07:37,494 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5515', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:37,494 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9742A4DD45480</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:37,541 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431
2024-08-07 21:07:37,541 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:37,541 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9742A4DE6554C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:37,659 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 7
2024-08-07 21:07:37,659 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:37,659 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-07 21:07:37,659 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:37,659 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-07 21:07:38,249 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/config.yaml
2024-08-07 21:07:38,250 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/output.log
2024-08-07 21:07:38,250 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/wandb-summary.json
2024-08-07 21:07:38,462 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 21:07:38,632 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65
2024-08-07 21:07:38,632 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290551', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:38,632 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9742A526CB8C1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:38,691 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c
2024-08-07 21:07:38,691 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5515', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:38,691 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9742A94C5206E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:38,691 INFO    wandb-upload_0:64391 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 21:07:38,891 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431
2024-08-07 21:07:38,891 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:38,891 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9742A9694CF98</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:38,891 INFO    wandb-upload_1:64391 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 21:07:39,388 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 8
2024-08-07 21:07:39,388 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: poll_exit
2024-08-07 21:07:39,388 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:39,388 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-07 21:07:39,388 DEBUG   SenderThread:64391 [sender.py:send_request():409] send_request: defer
2024-08-07 21:07:39,388 INFO    SenderThread:64391 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-07 21:07:39,388 INFO    SenderThread:64391 [job_builder.py:build():298] Attempting to build job artifact
2024-08-07 21:07:39,388 INFO    SenderThread:64391 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-07 21:07:39,402 INFO    SenderThread:64391 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-07 21:07:39,414 INFO    SenderThread:64391 [sender.py:transition_state():617] send defer: 9
2024-08-07 21:07:39,415 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: defer
2024-08-07 21:07:39,415 INFO    HandlerThread:64391 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-07 21:07:39,415 DEBUG   SenderThread:64391 [sender.py:send():382] send: artifact
2024-08-07 21:07:39,463 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-07 21:07:40,250 INFO    Thread-12 :64391 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240807_210733-uojuhshy/files/output.log
2024-08-07 21:07:40,334 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf
2024-08-07 21:07:40,334 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:40,335 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9742AF2F70117</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:40,615 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b
2024-08-07 21:07:40,615 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:40,615 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9742AF3270F65</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:40,875 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65
2024-08-07 21:07:40,875 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290551', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:40,875 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9742AD3B8B609</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:41,241 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c
2024-08-07 21:07:41,241 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5515', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:41,241 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9742B2CCC9C0F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:41,509 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431
2024-08-07 21:07:41,510 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:41,510 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9742B26A5259F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:41,597 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf
2024-08-07 21:07:41,597 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:41,597 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9742B4263E54B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:42,038 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b
2024-08-07 21:07:42,038 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:42,039 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9742B52B44D6B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:43,782 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf
2024-08-07 21:07:43,783 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:43,783 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9742BC4577C22</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:43,783 INFO    wandb-upload_3:64391 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 21:07:43,969 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65
2024-08-07 21:07:43,970 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290551', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:43,970 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9742BA44915CF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:44,466 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 21:07:44,599 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b
2024-08-07 21:07:44,599 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:44,599 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9742BEF8198E9</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:44,600 INFO    wandb-upload_4:64391 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-07 21:07:45,420 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c
2024-08-07 21:07:45,420 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5515', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:45,420 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9742C25BD4684</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:46,243 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431
2024-08-07 21:07:46,243 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:46,244 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9742C51C6503E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:48,868 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf
2024-08-07 21:07:48,868 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:48,868 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9742CD8568D26</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:49,241 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b
2024-08-07 21:07:49,241 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:49,241 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9742CFA3C66A5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:49,287 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65
2024-08-07 21:07:49,287 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290551', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:49,287 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9742CE6C833F5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:49,468 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 21:07:54,471 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 21:07:55,146 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=897659efd27e7f98efa05fa6f1d6715661b611ebec5de975998f37b016df7431
2024-08-07 21:07:55,146 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:55,147 ERROR   wandb-upload_1:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9742E64C61550</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:55,357 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=96565813b85fd016d15ad2bc8dafeff2327bdcdc7109e3f83f00544bf2e5e12c
2024-08-07 21:07:55,358 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5515', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:55,358 ERROR   wandb-upload_0:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9742E71B78D38</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:57,702 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d6e553f4049df4b696c2afeb23dbc37ea903929a107d27e33a3d76c71f5b43cf
2024-08-07 21:07:57,702 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:57,703 ERROR   wandb-upload_3:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9742EFCC2FC3D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:57,874 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130740Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=0fc1cc8b957af53ac5bb5a48d193056421480da4cf03f6d58e8675e2c70a248b
2024-08-07 21:07:57,874 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-MD5': 'PsnQsPOeVdCTjVJdiBuzBQ==', 'Content-Type': 'application/json', 'Content-Length': '31083', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:57,874 ERROR   wandb-upload_4:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/41/519/3ec9d0b0f39e55d0938d525d881bb305</Resource><Region>wandb-local</Region><RequestId>17E9742F023798C3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-07 21:07:59,473 DEBUG   HandlerThread:64391 [handler.py:handle_request():146] handle_request: keepalive
2024-08-07 21:07:59,652 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/uojuhshy/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240807%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240807T130737Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1268aa6e9cea4670751fd2858f8111f90529627c8c752d71f2c2095311bded65
2024-08-07 21:07:59,652 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '290551', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-07 21:07:59,652 ERROR   wandb-upload_2:64391 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/uojuhshy/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/uojuhshy/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9742F50616B95</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
