2024-08-08 20:05:15,489 INFO    StreamThr :345978 [internal.py:wandb_internal():86] W&B internal server running at pid: 345978, started at: 2024-08-08 20:05:15.489046
2024-08-08 20:05:15,490 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: status
2024-08-08 20:05:15,491 INFO    WriterThread:345978 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/run-rg1j7cha.wandb
2024-08-08 20:05:15,491 DEBUG   SenderThread:345978 [sender.py:send():382] send: header
2024-08-08 20:05:15,522 DEBUG   SenderThread:345978 [sender.py:send():382] send: run
2024-08-08 20:05:15,771 INFO    SenderThread:345978 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files
2024-08-08 20:05:15,771 INFO    SenderThread:345978 [sender.py:_start_run_threads():1136] run started: rg1j7cha with start time 1723118715.488999
2024-08-08 20:05:15,784 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 20:05:15,785 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: check_version
2024-08-08 20:05:15,906 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 20:05:15,916 DEBUG   HandlerThread:345978 [system_info.py:__init__():32] System info init
2024-08-08 20:05:15,916 DEBUG   HandlerThread:345978 [system_info.py:__init__():47] System info init done
2024-08-08 20:05:15,916 INFO    HandlerThread:345978 [system_monitor.py:start():194] Starting system monitor
2024-08-08 20:05:15,917 INFO    SystemMonitor:345978 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 20:05:15,917 INFO    HandlerThread:345978 [system_monitor.py:probe():214] Collecting system info
2024-08-08 20:05:15,917 INFO    SystemMonitor:345978 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 20:05:15,918 INFO    SystemMonitor:345978 [interfaces.py:start():190] Started disk monitoring
2024-08-08 20:05:15,919 INFO    SystemMonitor:345978 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 20:05:15,919 INFO    SystemMonitor:345978 [interfaces.py:start():190] Started memory monitoring
2024-08-08 20:05:15,920 INFO    SystemMonitor:345978 [interfaces.py:start():190] Started network monitoring
2024-08-08 20:05:15,926 DEBUG   HandlerThread:345978 [system_info.py:probe():196] Probing system
2024-08-08 20:05:15,927 DEBUG   HandlerThread:345978 [system_info.py:_probe_git():181] Probing git
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_info.py:_probe_git():189] Probing git done
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_info.py:probe():244] Probing system done
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T12:05:15.926971', 'startedAt': '2024-08-08T12:05:15.483693', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'gbmm'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1329.954, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 2451.521, 'min': 800.0, 'max': 5500.0}, {'current': 2523.016, 'min': 800.0, 'max': 5500.0}, {'current': 1482.369, 'min': 800.0, 'max': 5500.0}, {'current': 2602.314, 'min': 800.0, 'max': 5500.0}, {'current': 2508.824, 'min': 800.0, 'max': 5500.0}, {'current': 2602.057, 'min': 800.0, 'max': 5500.0}, {'current': 2450.944, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2517.683, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1649.457, 'min': 800.0, 'max': 5600.0}, {'current': 2603.255, 'min': 800.0, 'max': 5600.0}, {'current': 2578.696, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 2731.663, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 481.04553985595703}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 20:05:15,930 INFO    HandlerThread:345978 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 20:05:15,930 INFO    HandlerThread:345978 [system_monitor.py:probe():227] Publishing system info
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 20:05:15,930 DEBUG   HandlerThread:345978 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 20:05:16,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/conda-environment.yaml
2024-08-08 20:05:16,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/requirements.txt
2024-08-08 20:05:17,594 DEBUG   HandlerThread:345978 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 20:05:17,594 DEBUG   HandlerThread:345978 [system_info.py:_save_code():90] Saving code
2024-08-08 20:05:17,595 DEBUG   HandlerThread:345978 [system_info.py:_save_code():111] Saving code done
2024-08-08 20:05:17,595 DEBUG   HandlerThread:345978 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 20:05:17,616 DEBUG   HandlerThread:345978 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 20:05:17,617 INFO    HandlerThread:345978 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 20:05:17,618 DEBUG   SenderThread:345978 [sender.py:send():382] send: files
2024-08-08 20:05:17,618 INFO    SenderThread:345978 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 20:05:17,618 INFO    SenderThread:345978 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 20:05:17,618 INFO    SenderThread:345978 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 20:05:17,623 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 20:05:17,623 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 20:05:17,623 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: stop_status
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/conda-environment.yaml
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/wandb-metadata.json
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/diff.patch
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/code/llama/gmm.py
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/code/llama
2024-08-08 20:05:17,771 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/code
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: telemetry
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: config
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: metric
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: telemetry
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: metric
2024-08-08 20:05:17,820 WARNING SenderThread:345978 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: telemetry
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: telemetry
2024-08-08 20:05:17,820 DEBUG   SenderThread:345978 [sender.py:send():382] send: config
2024-08-08 20:05:17,883 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde
2024-08-08 20:05:17,883 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5247', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:17,883 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BF582B818684</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:17,979 DEBUG   SenderThread:345978 [sender.py:send():382] send: exit
2024-08-08 20:05:17,979 INFO    SenderThread:345978 [sender.py:send_exit():589] handling exit code: 1
2024-08-08 20:05:17,979 INFO    SenderThread:345978 [sender.py:send_exit():591] handling runtime: 2
2024-08-08 20:05:17,979 INFO    SenderThread:345978 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 20:05:17,979 INFO    SenderThread:345978 [sender.py:send_exit():597] send defer
2024-08-08 20:05:17,979 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:17,979 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 0
2024-08-08 20:05:17,979 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:17,979 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 0
2024-08-08 20:05:17,980 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 1
2024-08-08 20:05:17,980 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:17,980 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 1
2024-08-08 20:05:17,980 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:17,980 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 1
2024-08-08 20:05:17,980 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 2
2024-08-08 20:05:17,980 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:17,980 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 2
2024-08-08 20:05:17,980 INFO    HandlerThread:345978 [system_monitor.py:finish():203] Stopping system monitor
2024-08-08 20:05:17,980 DEBUG   SystemMonitor:345978 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-08 20:05:17,980 INFO    HandlerThread:345978 [interfaces.py:finish():202] Joined cpu monitor
2024-08-08 20:05:17,980 DEBUG   SystemMonitor:345978 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-08 20:05:17,980 INFO    HandlerThread:345978 [interfaces.py:finish():202] Joined disk monitor
2024-08-08 20:05:17,980 DEBUG   SystemMonitor:345978 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-08 20:05:17,985 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b
2024-08-08 20:05:17,985 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:17,985 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BF582EF0423B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:18,003 INFO    HandlerThread:345978 [interfaces.py:finish():202] Joined gpu monitor
2024-08-08 20:05:18,003 INFO    HandlerThread:345978 [interfaces.py:finish():202] Joined memory monitor
2024-08-08 20:05:18,003 INFO    HandlerThread:345978 [interfaces.py:finish():202] Joined network monitor
2024-08-08 20:05:18,003 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,003 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 2
2024-08-08 20:05:18,003 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 3
2024-08-08 20:05:18,003 DEBUG   SenderThread:345978 [sender.py:send():382] send: stats
2024-08-08 20:05:18,003 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:18,003 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 3
2024-08-08 20:05:18,003 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,003 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 3
2024-08-08 20:05:18,003 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 4
2024-08-08 20:05:18,004 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:18,004 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 4
2024-08-08 20:05:18,004 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 4
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 5
2024-08-08 20:05:18,004 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:18,004 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 5
2024-08-08 20:05:18,004 DEBUG   SenderThread:345978 [sender.py:send():382] send: summary
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 20:05:18,004 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 5
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 6
2024-08-08 20:05:18,004 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:18,004 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 6
2024-08-08 20:05:18,004 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,004 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 6
2024-08-08 20:05:18,005 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 20:05:18,205 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 7
2024-08-08 20:05:18,206 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:18,206 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 7
2024-08-08 20:05:18,206 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:18,206 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 7
2024-08-08 20:05:18,481 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55
2024-08-08 20:05:18,481 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293286', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:18,481 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BF582DA37E8F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:18,772 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/config.yaml
2024-08-08 20:05:18,772 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/wandb-summary.json
2024-08-08 20:05:18,772 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/output.log
2024-08-08 20:05:18,979 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 20:05:19,125 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b
2024-08-08 20:05:19,125 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:19,125 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BF5874F4136E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:19,125 INFO    wandb-upload_1:345978 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 20:05:19,347 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde
2024-08-08 20:05:19,347 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5247', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:19,347 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BF586EFBF27D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:19,347 INFO    wandb-upload_0:345978 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 20:05:19,835 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 8
2024-08-08 20:05:19,835 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: poll_exit
2024-08-08 20:05:19,835 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:19,835 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 8
2024-08-08 20:05:19,835 DEBUG   SenderThread:345978 [sender.py:send_request():409] send_request: defer
2024-08-08 20:05:19,835 INFO    SenderThread:345978 [sender.py:send_request_defer():613] handle sender defer: 8
2024-08-08 20:05:19,835 INFO    SenderThread:345978 [job_builder.py:build():298] Attempting to build job artifact
2024-08-08 20:05:19,836 INFO    SenderThread:345978 [job_builder.py:_get_source_type():428] is repo sourced job
2024-08-08 20:05:19,851 INFO    SenderThread:345978 [job_builder.py:build():404] adding wandb-job metadata file
2024-08-08 20:05:19,862 INFO    SenderThread:345978 [sender.py:transition_state():617] send defer: 9
2024-08-08 20:05:19,862 DEBUG   SenderThread:345978 [sender.py:send():382] send: artifact
2024-08-08 20:05:19,862 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: defer
2024-08-08 20:05:19,864 INFO    HandlerThread:345978 [handler.py:handle_request_defer():172] handle defer: 9
2024-08-08 20:05:19,980 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: poll_exit
2024-08-08 20:05:20,032 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55
2024-08-08 20:05:20,032 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293286', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:20,032 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BF5899BB3889</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:20,773 INFO    Thread-12 :345978 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_200515-rg1j7cha/files/output.log
2024-08-08 20:05:21,294 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3
2024-08-08 20:05:21,294 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:21,294 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BF58F6E697FD</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:21,359 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3
2024-08-08 20:05:21,359 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:21,360 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BF58F7A21D0E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:21,381 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b
2024-08-08 20:05:21,381 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:21,381 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BF58F670EB5C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:21,683 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde
2024-08-08 20:05:21,683 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5247', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:21,683 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BF590E15445A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:22,443 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3
2024-08-08 20:05:22,444 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:22,444 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BF593A212D5E</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:22,451 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3
2024-08-08 20:05:22,452 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:22,452 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BF593BECD552</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:22,537 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55
2024-08-08 20:05:22,538 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293286', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:22,538 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BF5930449051</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:24,621 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3
2024-08-08 20:05:24,621 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:24,621 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BF59BD017470</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:24,621 INFO    wandb-upload_3:345978 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 20:05:24,694 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3
2024-08-08 20:05:24,694 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:24,694 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BF59C04838CD</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:24,694 INFO    wandb-upload_4:345978 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 20:05:24,983 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 20:05:26,049 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b
2024-08-08 20:05:26,049 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:26,049 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BF59F915A277</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:26,647 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde
2024-08-08 20:05:26,647 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5247', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:26,648 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BF5A31DCA527</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:27,338 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55
2024-08-08 20:05:27,338 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293286', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:27,338 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BF5A4CA2E22F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:29,140 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3
2024-08-08 20:05:29,140 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:29,140 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BF5AC94247C7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:29,459 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3
2024-08-08 20:05:29,459 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:29,459 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BF5ADD5C6319</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:29,985 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 20:05:34,830 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6927143668a954bab64b27f84ca934b8146267b91d6ca8edde93c001d4f4258b
2024-08-08 20:05:34,830 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14196', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:34,830 ERROR   wandb-upload_1:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9BF5C1809A8AA</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:34,988 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 20:05:35,074 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=a120ef98e06b1694b5d2b9917925e6e749671626b1745e9962b55cab289dacde
2024-08-08 20:05:35,074 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5247', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:35,074 ERROR   wandb-upload_0:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9BF5C2C1F4FC6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:36,913 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/rg1j7cha/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120517Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=e74473c3ee43ea62eb450afd9dcdc5105059fbf82049d14e6fefb35be952dd55
2024-08-08 20:05:36,914 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '293286', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:36,914 ERROR   wandb-upload_2:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/rg1j7cha/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/rg1j7cha/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9BF5C691D27F6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:37,380 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=d1d161f1eb0c58ae44a6e0d7ec0f61e2c0ff9ee46bbb3bc11bc04412eb1771c3
2024-08-08 20:05:37,380 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-MD5': 'md9Ze/vY9I2UAyrVcasw7A==', 'Content-Type': 'application/json', 'Content-Length': '25169', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:37,380 ERROR   wandb-upload_4:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/99df597bfbd8f48d94032ad571ab30ec</Resource><Region>wandb-local</Region><RequestId>17E9BF5CB46A7E2F</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:37,923 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T120521Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-meta-md5&X-User=mobius&X-Amz-Signature=76d5dc906faf3d83fa005fabe29be760f5a1cc6238ecaef5394a2d19298686b3
2024-08-08 20:05:37,923 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'x-amz-meta-md5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-MD5': 'wt+PCmy04FImuFe2zcU/TQ==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '5025', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 20:05:37,923 ERROR   wandb-upload_3:345978 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Key><BucketName>local-files</BucketName><Resource>/local-files/wandb_artifacts/42/532/c2df8f0a6cb4e05226b857b6cdc53f4d</Resource><Region>wandb-local</Region><RequestId>17E9BF5CD5E59E61</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 20:05:39,990 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: keepalive
2024-08-08 20:05:44,993 DEBUG   HandlerThread:345978 [handler.py:handle_request():146] handle_request: keepalive
