2024-08-08 13:58:07,324 INFO    StreamThr :245717 [internal.py:wandb_internal():86] W&B internal server running at pid: 245717, started at: 2024-08-08 13:58:07.324193
2024-08-08 13:58:07,325 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status
2024-08-08 13:58:07,326 INFO    WriterThread:245717 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/run-e1ixy8jt.wandb
2024-08-08 13:58:07,326 DEBUG   SenderThread:245717 [sender.py:send():382] send: header
2024-08-08 13:58:07,358 DEBUG   SenderThread:245717 [sender.py:send():382] send: run
2024-08-08 13:58:07,600 INFO    SenderThread:245717 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files
2024-08-08 13:58:07,600 INFO    SenderThread:245717 [sender.py:_start_run_threads():1136] run started: e1ixy8jt with start time 1723096687.324136
2024-08-08 13:58:07,606 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: check_version
2024-08-08 13:58:07,606 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: check_version
2024-08-08 13:58:07,715 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: run_start
2024-08-08 13:58:07,730 DEBUG   HandlerThread:245717 [system_info.py:__init__():32] System info init
2024-08-08 13:58:07,730 DEBUG   HandlerThread:245717 [system_info.py:__init__():47] System info init done
2024-08-08 13:58:07,730 INFO    HandlerThread:245717 [system_monitor.py:start():194] Starting system monitor
2024-08-08 13:58:07,730 INFO    SystemMonitor:245717 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-08 13:58:07,731 INFO    HandlerThread:245717 [system_monitor.py:probe():214] Collecting system info
2024-08-08 13:58:07,732 INFO    SystemMonitor:245717 [interfaces.py:start():190] Started cpu monitoring
2024-08-08 13:58:07,732 INFO    SystemMonitor:245717 [interfaces.py:start():190] Started disk monitoring
2024-08-08 13:58:07,733 INFO    SystemMonitor:245717 [interfaces.py:start():190] Started gpu monitoring
2024-08-08 13:58:07,733 INFO    SystemMonitor:245717 [interfaces.py:start():190] Started memory monitoring
2024-08-08 13:58:07,734 INFO    SystemMonitor:245717 [interfaces.py:start():190] Started network monitoring
2024-08-08 13:58:07,748 DEBUG   HandlerThread:245717 [system_info.py:probe():196] Probing system
2024-08-08 13:58:07,751 DEBUG   HandlerThread:245717 [system_info.py:_probe_git():181] Probing git
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_info.py:_probe_git():189] Probing git done
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_info.py:probe():244] Probing system done
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-44-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-08T05:58:07.748909', 'startedAt': '2024-08-08T05:58:07.319199', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/llama2-7b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:100000]', '--output_dir', '/home/rwkv/JL/out_model/llama-test', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '32', '--save_strategy', 'steps', '--save_steps', '4000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True', '--run_name', 'ttt'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': '74dce7f004b5b16bfd24c8ca22e737aee6ff0769'}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1234.1275714285714, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1100.197, 'min': 800.0, 'max': 5500.0}, {'current': 1667.916, 'min': 800.0, 'max': 5500.0}, {'current': 1100.0, 'min': 800.0, 'max': 5500.0}, {'current': 1691.21, 'min': 800.0, 'max': 5500.0}, {'current': 1100.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1100.029, 'min': 800.0, 'max': 5500.0}, {'current': 1096.839, 'min': 800.0, 'max': 5500.0}, {'current': 1198.623, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1100.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1100.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1100.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 2067.333, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 477.9758491516113}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.55397415161133}}
2024-08-08 13:58:07,757 INFO    HandlerThread:245717 [system_monitor.py:probe():224] Finished collecting system info
2024-08-08 13:58:07,757 INFO    HandlerThread:245717 [system_monitor.py:probe():227] Publishing system info
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-08 13:58:07,757 DEBUG   HandlerThread:245717 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-08 13:58:08,601 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/conda-environment.yaml
2024-08-08 13:58:08,601 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/requirements.txt
2024-08-08 13:58:09,427 DEBUG   HandlerThread:245717 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-08 13:58:09,427 DEBUG   HandlerThread:245717 [system_info.py:_save_code():90] Saving code
2024-08-08 13:58:09,429 DEBUG   HandlerThread:245717 [system_info.py:_save_code():111] Saving code done
2024-08-08 13:58:09,429 DEBUG   HandlerThread:245717 [system_info.py:_save_patches():128] Saving git patches
2024-08-08 13:58:09,470 DEBUG   HandlerThread:245717 [system_info.py:_save_patches():170] Saving git patches done
2024-08-08 13:58:09,471 INFO    HandlerThread:245717 [system_monitor.py:probe():229] Finished publishing system info
2024-08-08 13:58:09,475 DEBUG   SenderThread:245717 [sender.py:send():382] send: files
2024-08-08 13:58:09,475 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-08 13:58:09,475 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-08 13:58:09,476 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file diff.patch with policy now
2024-08-08 13:58:09,483 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 13:58:09,483 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: stop_status
2024-08-08 13:58:09,485 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/conda-environment.yaml
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/wandb-metadata.json
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/diff.patch
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/code/llama/gmm.py
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/code/llama
2024-08-08 13:58:09,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/code
2024-08-08 13:58:09,720 DEBUG   SenderThread:245717 [sender.py:send():382] send: telemetry
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: config
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: telemetry
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:09,721 WARNING SenderThread:245717 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: telemetry
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: telemetry
2024-08-08 13:58:09,721 DEBUG   SenderThread:245717 [sender.py:send():382] send: config
2024-08-08 13:58:09,745 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:09,745 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:09,745 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB4F58938670</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:09,814 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:09,814 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:09,814 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB4F5947F2A6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:10,179 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:10,179 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:10,179 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB4F5CD71251</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:10,600 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/output.log
2024-08-08 13:58:10,913 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:10,913 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:10,913 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB4F9E4F6451</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:10,913 INFO    wandb-upload_1:245717 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 13:58:10,918 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:10,918 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:10,918 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB4F9E80E791</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:10,918 INFO    wandb-upload_0:245717 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-08 13:58:11,632 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:11,632 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:11,632 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB4FB76EB0C6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:12,601 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/output.log
2024-08-08 13:58:12,722 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:13,246 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:13,247 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:13,247 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB50297644F6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:13,423 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:13,423 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:13,423 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB5033E5FDB3</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:14,052 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:14,052 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:14,052 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB50551611EF</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:17,723 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:17,993 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:17,993 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:17,993 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB51445A45E1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:18,364 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:18,364 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:18,364 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB515A837A8C</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:18,485 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:18,485 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:18,485 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB515C9500D5</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:22,723 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:23,671 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 13:58:23,672 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:23,672 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:23,672 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:23,672 DEBUG   SenderThread:245717 [sender.py:send():382] send: metric
2024-08-08 13:58:23,673 DEBUG   SenderThread:245717 [sender.py:send():382] send: history
2024-08-08 13:58:23,673 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: summary_record
2024-08-08 13:58:23,673 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 13:58:24,482 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 13:58:24,482 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: stop_status
2024-08-08 13:58:24,483 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 13:58:24,603 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/wandb-summary.json
2024-08-08 13:58:26,603 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/output.log
2024-08-08 13:58:27,245 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:27,245 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:27,246 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB536BD67E5D</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:27,436 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:27,436 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:27,436 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB537736D219</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:27,505 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:27,505 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:27,505 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB53797DCDBB</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:28,708 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:33,708 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:36,240 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 13:58:36,241 DEBUG   SenderThread:245717 [sender.py:send():382] send: history
2024-08-08 13:58:36,241 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: summary_record
2024-08-08 13:58:36,242 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 13:58:36,605 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/wandb-summary.json
2024-08-08 13:58:38,605 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/output.log
2024-08-08 13:58:39,244 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:39,484 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 13:58:39,484 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 13:58:39,485 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: stop_status
2024-08-08 13:58:39,606 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/config.yaml
2024-08-08 13:58:44,051 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=2e7f879e3e09db26545a152720542391519ebaabc3f1c1b729762f7d77e3a383
2024-08-08 13:58:44,051 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14190', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:44,051 ERROR   wandb-upload_1:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E9AB575159763B</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:44,654 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:45,506 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/diff.patch?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=6faa7efb6b2bec445af61d5217bbd1f75c810cb98bc85fcc3107b6cb422f846f
2024-08-08 13:58:45,506 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '291650', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:45,506 ERROR   wandb-upload_2:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/diff.patch</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/diff.patch</Resource><Region>wandb-local</Region><RequestId>17E9AB579CF5C2B6</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:46,286 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240808%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240808T055809Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=d0158374f5df237c2ac42c55c9754d54eefe679f2a05fafbd0db295ce41c0dff
2024-08-08 13:58:46,286 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5244', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-08 13:58:46,286 ERROR   wandb-upload_0:245717 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/e1ixy8jt/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/e1ixy8jt/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E9AB57D19A2A8A</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-08 13:58:48,864 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: partial_history
2024-08-08 13:58:48,865 DEBUG   SenderThread:245717 [sender.py:send():382] send: history
2024-08-08 13:58:48,865 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: summary_record
2024-08-08 13:58:48,866 INFO    SenderThread:245717 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-08 13:58:49,607 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/wandb-summary.json
2024-08-08 13:58:49,866 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
2024-08-08 13:58:50,607 INFO    Thread-12 :245717 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240808_135807-e1ixy8jt/files/output.log
2024-08-08 13:58:54,482 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: stop_status
2024-08-08 13:58:54,482 DEBUG   SenderThread:245717 [sender.py:send_request():409] send_request: stop_status
2024-08-08 13:58:54,483 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-08 13:58:55,702 DEBUG   HandlerThread:245717 [handler.py:handle_request():146] handle_request: status_report
